import { NextResponse } from 'next/server';
import { getSession } from '@/lib/auth';
import { db } from '@/lib/db';
import ExcelJS from 'exceljs';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
export const runtime='nodejs';

type Row=(string|number|null|undefined)[];
const clean=(v:any)=>v===null||v===undefined?'':String(v);

function titleFor(jenis:string){const m:Record<string,string>={siswa:'Daftar Siswa',kehadiran:'Rekap Kehadiran',nilai:'Laporan Nilai',prestasi:'Rekap Prestasi',catatan:'Catatan Wali Kelas',tindak:'Tindak Lanjut',komunikasi:'Komunikasi Orang Tua',agenda:'Agenda Kelas'};return m[jenis]||'Laporan Kelas';}

async function reportData(sql:ReturnType<typeof db>,licenseId:string,jenis:string,month:string,subjectId?:string|null){
  if(jenis==='siswa'){const r=await sql`SELECT nis,nisn,name,gender,guardian_name,guardian_phone,phone,address,status FROM students WHERE license_id=${licenseId} AND status<>'Dihapus' ORDER BY name`;return {headers:['NIS','NISN','Nama Siswa','Jenis Kelamin','Orang Tua/Wali','No. Orang Tua','No. Siswa','Alamat','Status'],rows:r.map(x=>[x.nis,x.nisn,x.name,x.gender,x.guardian_name,x.guardian_phone,x.phone,x.address,x.status])};}
  if(jenis==='kehadiran'){const from=`${month}-01`;const r=await sql`SELECT st.nis,st.name,COUNT(*) FILTER(WHERE ar.status='Hadir') hadir,COUNT(*) FILTER(WHERE ar.status='Sakit') sakit,COUNT(*) FILTER(WHERE ar.status='Izin') izin,COUNT(*) FILTER(WHERE ar.status='Alfa') alfa,COUNT(*) FILTER(WHERE ar.status='Terlambat') terlambat,COUNT(*) FILTER(WHERE ar.status='Dispensasi') dispensasi FROM students st LEFT JOIN attendance_days ad ON ad.license_id=${licenseId} AND ad.attendance_date>=${from}::date AND ad.attendance_date<(${from}::date+interval '1 month') LEFT JOIN attendance_records ar ON ar.attendance_day_id=ad.id AND ar.student_id=st.id WHERE st.license_id=${licenseId} AND st.status<>'Dihapus' GROUP BY st.id,st.nis,st.name ORDER BY st.name`;return {headers:['NIS','Nama Siswa','Hadir','Sakit','Izin','Alfa','Terlambat','Dispensasi'],rows:r.map(x=>[x.nis,x.name,x.hadir,x.sakit,x.izin,x.alfa,x.terlambat,x.dispensasi])};}
  if(jenis==='nilai'){const r=subjectId?await sql`SELECT st.nis,st.name student_name,su.name subject_name,a.name assessment_name,a.category,a.semester,a.max_score,ss.score,ss.remedial_score FROM assessments a JOIN subjects su ON su.id=a.subject_id CROSS JOIN students st LEFT JOIN student_scores ss ON ss.assessment_id=a.id AND ss.student_id=st.id WHERE a.license_id=${licenseId} AND st.license_id=${licenseId} AND st.status<>'Dihapus' AND a.subject_id=${subjectId} ORDER BY su.name,a.assessment_date,st.name`:await sql`SELECT st.nis,st.name student_name,su.name subject_name,a.name assessment_name,a.category,a.semester,a.max_score,ss.score,ss.remedial_score FROM assessments a JOIN subjects su ON su.id=a.subject_id CROSS JOIN students st LEFT JOIN student_scores ss ON ss.assessment_id=a.id AND ss.student_id=st.id WHERE a.license_id=${licenseId} AND st.license_id=${licenseId} AND st.status<>'Dihapus' ORDER BY su.name,a.assessment_date,st.name`;return {headers:['NIS','Nama Siswa','Mata Pelajaran','Penilaian','Jenis','Semester','Nilai Maks.','Nilai','Remedial','Nilai Digunakan'],rows:r.map(x=>[x.nis,x.student_name,x.subject_name,x.assessment_name,x.category,x.semester,x.max_score,x.score,x.remedial_score,x.remedial_score??x.score])};}
  if(jenis==='prestasi'){const r=await sql`SELECT st.nis,st.name,a.title,a.category,a.level,a.organizer,a.rank,a.achieved_at FROM achievements a JOIN students st ON st.id=a.student_id WHERE a.license_id=${licenseId} ORDER BY a.achieved_at DESC`;return {headers:['NIS','Nama Siswa','Prestasi','Kategori','Tingkat','Penyelenggara','Peringkat','Tanggal'],rows:r.map(x=>[x.nis,x.name,x.title,x.category,x.level,x.organizer,x.rank,x.achieved_at])};}
  if(jenis==='catatan'){const r=await sql`SELECT st.nis,st.name,n.category,n.title,n.content,n.status,n.occurred_at FROM student_notes n JOIN students st ON st.id=n.student_id WHERE n.license_id=${licenseId} ORDER BY n.occurred_at DESC`;return {headers:['NIS','Nama Siswa','Kategori','Judul','Catatan','Status','Tanggal'],rows:r.map(x=>[x.nis,x.name,x.category,x.title,x.content,x.status,x.occurred_at])};}
  if(jenis==='tindak'){const r=await sql`SELECT st.nis,COALESCE(st.name,'Umum') name,f.title,f.action,f.due_date,f.status,f.result FROM follow_ups f LEFT JOIN students st ON st.id=f.student_id WHERE f.license_id=${licenseId} ORDER BY f.due_date NULLS LAST`;return {headers:['NIS','Nama Siswa','Tindak Lanjut','Tindakan','Target','Status','Hasil'],rows:r.map(x=>[x.nis,x.name,x.title,x.action,x.due_date,x.status,x.result])};}
  if(jenis==='komunikasi'){const r=await sql`SELECT st.nis,st.name,c.method,c.topic,c.result,c.communicated_at FROM parent_communications c JOIN students st ON st.id=c.student_id WHERE c.license_id=${licenseId} ORDER BY c.communicated_at DESC`;return {headers:['NIS','Nama Siswa','Metode','Topik','Hasil','Tanggal'],rows:r.map(x=>[x.nis,x.name,x.method,x.topic,x.result,x.communicated_at])};}
  const r=await sql`SELECT title,category,agenda_date,agenda_time,description,is_done FROM class_agendas WHERE license_id=${licenseId} ORDER BY agenda_date,agenda_time`;return {headers:['Agenda','Kategori','Tanggal','Waktu','Keterangan','Status'],rows:r.map(x=>[x.title,x.category,x.agenda_date,x.agenda_time,x.description,x.is_done?'Selesai':'Terjadwal'])};
}

async function makeXlsx(title:string,subtitle:string,headers:string[],rows:Row[]){const wb=new ExcelJS.Workbook();wb.creator='KelasKita';const ws=wb.addWorksheet('Laporan',{views:[{state:'frozen',ySplit:4}]});ws.mergeCells(1,1,1,headers.length);const t=ws.getCell(1,1);t.value='KelasKita · '+title;t.font={bold:true,size:16,color:{argb:'FF0F2D6B'}};ws.mergeCells(2,1,2,headers.length);ws.getCell(2,1).value=subtitle;ws.getCell(2,1).font={size:10,color:{argb:'FF667085'}};ws.addRow([]);const hr=ws.addRow(headers);hr.font={bold:true,color:{argb:'FFFFFFFF'}};hr.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF0F2D6B'}};hr.alignment={vertical:'middle'};rows.forEach(row=>ws.addRow(row.map(v=>clean(v))));ws.autoFilter={from:{row:4,column:1},to:{row:4,column:headers.length}};headers.forEach((_,i)=>{const col=ws.getColumn(i+1);let w=headers[i].length+3;col.eachCell({includeEmpty:true},c=>{w=Math.max(w,Math.min(42,clean(c.value).length+2))});col.width=Math.min(42,w)});ws.eachRow((row,n)=>{row.height=n<=2?22:19;if(n>4&&n%2===0)row.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFF7F9FC'}}});return Buffer.from(await wb.xlsx.writeBuffer());}

async function makePdf(title:string,subtitle:string,headers:string[],rows:Row[]){const pdf=await PDFDocument.create();const font=await pdf.embedFont(StandardFonts.Helvetica);const bold=await pdf.embedFont(StandardFonts.HelveticaBold);const pageSize:[number,number]=[841.89,595.28];let page=pdf.addPage(pageSize);let y=557;const margin=34;const rowH=18;const maxCols=Math.min(headers.length,8);const colW=(pageSize[0]-margin*2)/maxCols;const drawHeader=()=>{page.drawText('KelasKita · '+title,{x:margin,y,font:bold,size:15,color:rgb(.06,.18,.42)});y-=18;page.drawText(subtitle,{x:margin,y,font,size:8,color:rgb(.4,.44,.52)});y-=25;for(let i=0;i<maxCols;i++){page.drawRectangle({x:margin+i*colW,y:y-rowH+4,width:colW,height:rowH,color:rgb(.06,.18,.42)});page.drawText(headers[i].slice(0,24),{x:margin+i*colW+4,y:y-9,font:bold,size:7,color:rgb(1,1,1)})}y-=rowH;};drawHeader();for(const row of rows){if(y<45){page=pdf.addPage(pageSize);y=557;drawHeader()}for(let i=0;i<maxCols;i++){const val=clean(row[i]).replace(/\s+/g,' ').slice(0,36);page.drawText(val,{x:margin+i*colW+4,y:y-9,font,size:6.8,color:rgb(.12,.16,.23)})}y-=rowH;}return Buffer.from(await pdf.save());}

export async function GET(req:Request){const s=await getSession();if(!s)return NextResponse.json({message:'Sesi berakhir.'},{status:401});try{const u=new URL(req.url);const jenis=u.searchParams.get('jenis')||'siswa';const format=u.searchParams.get('format')==='pdf'?'pdf':'xlsx';const month=u.searchParams.get('bulan')||new Date().toISOString().slice(0,7);const subjectId=u.searchParams.get('subject_id');const sql=db();const p=await sql`SELECT teacher_name,school_name,class_name,academic_year FROM licenses WHERE id=${s.licenseId}`;const profile=p[0];const data=await reportData(sql,s.licenseId,jenis,month,subjectId);const title=titleFor(jenis);const subtitle=`${profile.school_name} · ${profile.class_name} · ${profile.academic_year}${jenis==='kehadiran'?' · '+month:''}`;const body=format==='pdf'?await makePdf(title,subtitle,data.headers,data.rows):await makeXlsx(title,subtitle,data.headers,data.rows);const ext=format==='pdf'?'pdf':'xlsx';return new NextResponse(new Uint8Array(body),{headers:{'Content-Type':format==='pdf'?'application/pdf':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':`attachment; filename="KelasKita_${jenis}_${month}.${ext}"`}})}catch(e){console.error(e);return NextResponse.json({message:'Laporan belum berhasil dibuat.'},{status:500})}}
