import { NextResponse } from 'next/server';
import { getSession } from '@/lib/auth';
import { db } from '@/lib/db';
import ExcelJS from 'exceljs';
export const runtime='nodejs';

const headers=['NIS','NISN','Nama','Jenis Kelamin','Tempat Lahir','Tanggal Lahir','Alamat','Nama Wali Siswa','No. Wali Siswa','No. Siswa'];
export async function GET(){const s=await getSession();if(!s)return NextResponse.json({message:'Sesi berakhir.'},{status:401});const wb=new ExcelJS.Workbook();const ws=wb.addWorksheet('Siswa');ws.addRow(headers);ws.addRow(['24001','009881001','Nama Siswa','Laki-laki','Palu','2010-01-15','Alamat siswa','Nama Wali','081234567890','081234567891']);ws.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};ws.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF0F2D6B'}};ws.columns.forEach(c=>c.width=20);const b=Buffer.from(await wb.xlsx.writeBuffer());return new NextResponse(new Uint8Array(b),{headers:{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':'attachment; filename="Template_Impor_Siswa_KelasKita.xlsx"'}})}
export async function POST(req:Request){const s=await getSession();if(!s)return NextResponse.json({message:'Sesi berakhir.'},{status:401});try{const form=await req.formData();const file=form.get('file');if(!(file instanceof File))return NextResponse.json({message:'File Excel belum dipilih.'},{status:400});const wb=new ExcelJS.Workbook();await wb.xlsx.load(await file.arrayBuffer());const ws=wb.worksheets[0];if(!ws)return NextResponse.json({message:'Sheet tidak ditemukan.'},{status:400});const head:Record<string,number>={};ws.getRow(1).eachCell((c,col)=>head[String(c.value||'').trim().toLowerCase()]=col);const get=(row:any,name:string)=>{const c=head[name.toLowerCase()];return c?String(row.getCell(c).text||'').trim():''};const rows:any[]=[];ws.eachRow((row,n)=>{if(n===1)return;const name=get(row,'Nama');if(!name)return;rows.push({nis:get(row,'NIS')||null,nisn:get(row,'NISN')||null,name,gender:get(row,'Jenis Kelamin')||null,birth_place:get(row,'Tempat Lahir')||null,birth_date:get(row,'Tanggal Lahir')||null,address:get(row,'Alamat')||null,guardian_name:get(row,'Nama Wali Siswa')||null,guardian_phone:get(row,'No. Wali Siswa')||null,phone:get(row,'No. Siswa')||null})});if(!rows.length)return NextResponse.json({message:'Tidak ada baris siswa yang dapat diimpor.'},{status:400});const sql=db();const inserted=await sql`INSERT INTO students(license_id,nis,nisn,name,gender,birth_place,birth_date,address,guardian_name,guardian_phone,phone)
SELECT ${s.licenseId},x.nis,x.nisn,x.name,x.gender,x.birth_place,NULLIF(x.birth_date,'')::date,x.address,x.guardian_name,x.guardian_phone,x.phone
FROM jsonb_to_recordset(${JSON.stringify(rows)}::jsonb) AS x(nis text,nisn text,name text,gender text,birth_place text,birth_date text,address text,guardian_name text,guardian_phone text,phone text)
ON CONFLICT DO NOTHING RETURNING id`;return NextResponse.json({ok:true,total:rows.length,inserted:inserted.length,skipped:rows.length-inserted.length})}catch(e){console.error(e);return NextResponse.json({message:'File siswa belum berhasil diimpor. Pastikan format sesuai template.'},{status:500})}}
