import Link from 'next/link';
import { ArrowRight, BookOpen, CalendarDays, ClipboardCheck, FileText, ShieldCheck, UsersRound } from 'lucide-react';
import Brand from '@/components/Brand';

export default function Landing(){return <main className="landing">
  <nav className="kk-container landing-nav"><Brand/><div className="landing-nav-actions"><Link className="btn btn-ghost" href="/demo">Coba Demo</Link><Link className="btn btn-ghost" href="/masuk">Masuk</Link><Link className="btn btn-dark" href="/beli">Beli Lisensi</Link></div></nav>
  <section className="kk-container hero"><div><span className="pill">Ruang kerja digital wali kelas</span><h1>Kelola kelas dengan <span>lebih tenang.</span></h1><p>KelasKita menyatukan siswa, kehadiran, nilai, mata pelajaran, jadwal, catatan, prestasi, tindak lanjut, administrasi, dan laporan dalam satu aplikasi yang dibuat khusus untuk wali kelas.</p><div className="hero-actions"><Link className="btn btn-primary" href="/beli">Beli KelasKita Rp99.000 <ArrowRight size={17}/></Link><Link className="btn btn-ghost" href="/demo">Coba Mode Demo</Link></div><div className="hero-note">Sekali bayar. Pembayaran diverifikasi manual sebelum kode lisensi dan PIN diterbitkan.</div></div>
    <div className="preview-shell"><div className="preview-inner"><div className="mini-head"><div><small>Selamat pagi,</small><div className="mini-title">Ibu Rina</div></div><img src="/brand/kelaskita-mark.png" alt=""/></div><div className="mini-stats"><div className="mini-stat"><small>Hadir</small><b>32</b></div><div className="mini-stat"><small>Akademik</small><b>83,7</b></div><div className="mini-stat"><small>Perhatian</small><b>3</b></div></div><div className="attention-card"><b>Perlu perhatian hari ini</b><div className="attention-item"><div><b>Ahmad Fauzan</b><small>2 mata pelajaran di bawah ketuntasan</small></div><span className="badge badge-warn">Tinjau</span></div><div className="attention-item"><div><b>Fadli Akbar</b><small>Tindak lanjut kehadiran</small></div><span className="badge badge-info">Hari ini</span></div></div><div className="attention-card"><b>Pelajaran berikutnya</b><p>09.15 · Produktif DKV · Lab DKV</p></div></div></div>
  </section>
  <section className="kk-container"><div className="feature-grid"><Feature icon={<ClipboardCheck/>} title="Kehadiran cepat" text="Ambil absensi, lihat pola alfa dan keterlambatan, lalu unduh rekap Excel atau PDF."/><Feature icon={<BookOpen/>} title="Nilai & akademik" text="Atur mata pelajaran, penilaian, nilai harian, ulangan, semester, remedial, dan batas ketuntasan."/><Feature icon={<CalendarDays/>} title="Jadwal pelajaran" text="Susun jadwal mingguan dan tampilkan pelajaran hari ini langsung di Beranda."/><Feature icon={<UsersRound/>} title="Siswa 360°" text="Kehadiran, akademik, catatan, prestasi, tindak lanjut, dan data wali tersusun dalam satu profil."/><Feature icon={<FileText/>} title="Administrasi kelas" text="Catatan rapor, checklist administrasi, surat otomatis, struktur kelas, jadwal piket, dan arsip tahun ajaran."/><Feature icon={<ShieldCheck/>} title="Lisensi pribadi" text="Setiap pelanggan masuk menggunakan kode lisensi dan PIN dengan ruang data yang terpisah."/></div></section>
  <section className="kk-container price-band"><div className="price-card"><div><small>LISENSI KELASKITA</small><div className="price">Rp99.000 <small>/ lisensi</small></div><p>Satu ruang kerja lengkap untuk satu wali kelas.</p></div><div className="price-actions"><Link className="btn btn-primary" href="/beli">Beli Sekarang</Link><Link className="btn light-btn" href="/demo">Coba Demo</Link></div></div></section>
</main>}
function Feature({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="feature-card"><span className="feature-icon">{icon}</span><h3>{title}</h3><p>{text}</p></div>}
