import Link from 'next/link';
import { ArrowRight, BookOpen, CalendarDays, ClipboardCheck, FileText, ShieldCheck, UsersRound } from 'lucide-react';
import Brand from '@/components/Brand';

export default function Landing(){return <main className="landing">
  <nav className="kk-container landing-nav"><Brand/><div style={{display:'flex',gap:10}}><Link className="btn btn-ghost" href="/demo">Coba Demo</Link><Link className="btn btn-dark" href="/masuk">Masuk</Link></div></nav>
  <section className="kk-container hero"><div><span className="pill">Ruang kerja digital wali kelas</span><h1>Kelola kelas dengan <span>lebih tenang.</span></h1><p>KelasKita menyatukan siswa, kehadiran, nilai, mata pelajaran, jadwal, catatan, prestasi, tindak lanjut, komunikasi orang tua, dan laporan dalam satu aplikasi yang dibuat khusus untuk wali kelas.</p><div className="hero-actions"><Link className="btn btn-primary" href="/demo">Coba Mode Demo <ArrowRight size={17}/></Link><Link className="btn btn-ghost" href="/masuk">Saya sudah punya lisensi</Link></div><div className="hero-note">Mode demo menggunakan data contoh dan tidak menulis ke database pelanggan.</div></div>
    <div className="preview-shell"><div className="preview-inner"><div className="mini-head"><div><small style={{color:'#7a849b'}}>Selamat pagi,</small><div className="mini-title">Ibu Rina</div></div><img src="/brand/kelaskita-mark.png" alt="" style={{width:44,height:44,objectFit:'contain'}}/></div><div className="mini-stats"><div className="mini-stat"><small>Hadir</small><b>32</b></div><div className="mini-stat"><small>Akademik</small><b>83,7</b></div><div className="mini-stat"><small>Perhatian</small><b>3</b></div></div><div className="attention-card"><b>Perlu perhatian hari ini</b><div className="attention-item"><div><b>Ahmad Fauzan</b><small style={{display:'block',color:'#788197'}}>2 mata pelajaran di bawah ketuntasan</small></div><span className="badge badge-warn">Tinjau</span></div><div className="attention-item"><div><b>Fadli Akbar</b><small style={{display:'block',color:'#788197'}}>Tindak lanjut kehadiran</small></div><span className="badge badge-info">Hari ini</span></div></div><div className="attention-card"><b>Pelajaran berikutnya</b><p style={{margin:'10px 0 0',color:'#6f7890'}}>09.15 · Produktif DKV · Lab DKV</p></div></div></div>
  </section>
  <section className="kk-container"><div className="feature-grid"><Feature icon={<ClipboardCheck/>} title="Kehadiran cepat" text="Semua siswa otomatis Hadir. Guru cukup mengubah siswa yang sakit, izin, alfa, terlambat, atau dispensasi."/><Feature icon={<BookOpen/>} title="Nilai & akademik" text="Atur mata pelajaran, penilaian, nilai harian, ulangan, semester, remedial, dan batas ketuntasan."/><Feature icon={<CalendarDays/>} title="Jadwal pelajaran" text="Susun jadwal mingguan dan tampilkan pelajaran hari ini langsung di Beranda."/><Feature icon={<UsersRound/>} title="Siswa 360°" text="Identitas, orang tua, akademik, catatan, prestasi, dan tindak lanjut tersusun per siswa."/><Feature icon={<FileText/>} title="Excel & PDF" text="Unduh laporan siswa, absensi, nilai, prestasi, tindak lanjut, komunikasi, dan agenda dengan format rapi."/><Feature icon={<ShieldCheck/>} title="Lisensi pribadi" text="Setiap pelanggan masuk menggunakan kode lisensi dan PIN, dengan ruang data yang terpisah."/></div></section>
  <section className="kk-container price-band"><div className="price-card"><div><small style={{color:'#aeb8d2'}}>LISENSI KELASKITA</small><div className="price">Rp99.000 <small>/ lisensi</small></div><p style={{color:'#c0cee3',marginBottom:0}}>Satu ruang kerja lengkap untuk satu wali kelas.</p></div><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><Link className="btn btn-primary" href="/demo">Coba Demo</Link><Link className="btn" style={{background:'#fff',color:'#0f2d6b'}} href="/masuk">Masuk dengan Lisensi</Link></div></div></section>
</main>}
function Feature({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="feature-card">{icon}<h3>{title}</h3><p>{text}</p></div>}
