'use client';
import { useEffect,useMemo,useState } from 'react';
import { useRouter } from 'next/navigation';
import { demoData } from '@/lib/demo-data';
import { Activity, Award, Bell, BookOpenCheck, CalendarDays, Check, ChevronRight, ClipboardCheck, Clock3, FileBarChart, FileText, GraduationCap, House, LogOut, Menu, MessageCircle, NotebookPen, Plus, Search, Settings, ShieldAlert, Sparkles, Trophy, UserRoundPlus, UsersRound, X } from 'lucide-react';

type Mode='demo'|'real';
type Student={id:string;nis?:string;nisn?:string;name:string;gender?:string;guardian_name?:string;guardian_phone?:string;phone?:string;address?:string;status?:string};
type Attendance={student_id:string;status:string;note?:string};
type DataShape={profile:any;students:Student[];attendance:Attendance[];notes:any[];achievements:any[];followUps:any[];communications:any[];agendas:any[]};
type View='beranda'|'siswa'|'kehadiran'|'catatan'|'prestasi'|'tindak'|'orangtua'|'agenda'|'laporan'|'pengaturan';
type ModalType='siswa'|'catatan'|'prestasi'|'tindak'|'agenda'|'komunikasi'|'detail'|null;

const nav=[
  ['beranda','Beranda',House],['siswa','Siswa',UsersRound],['kehadiran','Kehadiran',ClipboardCheck],['catatan','Catatan',NotebookPen],['prestasi','Prestasi',Trophy],['tindak','Tindak Lanjut',Activity],['orangtua','Orang Tua',MessageCircle],['agenda','Agenda',CalendarDays],['laporan','Laporan',FileBarChart],['pengaturan','Pengaturan',Settings]
] as const;

function localDate(){const d=new Date();const y=d.getFullYear();const m=String(d.getMonth()+1).padStart(2,'0');const day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function indoDate(v?:string){if(!v)return '-';const d=new Date(v.length===10?`${v}T00:00:00`:v);return d.toLocaleDateString('id-ID',{day:'numeric',month:'short',year:'numeric'})}
function initials(name:string){return name.split(' ').slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function statusClass(status:string){if(/Selesai|Hadir|Aman|Aktif/.test(status))return'badge-good';if(/Alfa|Butuh|Nonaktif/.test(status))return'badge-danger';if(/Perlu|Belum|Terlambat|Menunggu/.test(status))return'badge-warn';return'badge-info'}

export default function KelasKitaApp({mode}:{mode:Mode}){
  const router=useRouter();
  const [data,setData]=useState<DataShape>(()=>JSON.parse(JSON.stringify(demoData)));
  const [view,setView]=useState<View>('beranda');
  const [loading,setLoading]=useState(mode==='real');
  const [search,setSearch]=useState('');
  const [modal,setModal]=useState<ModalType>(null);
  const [selected,setSelected]=useState<Student|null>(null);
  const [toast,setToast]=useState('');
  const [moreOpen,setMoreOpen]=useState(false);
  const [attendanceMap,setAttendanceMap]=useState<Record<string,string>>({});
  const today=localDate();

  async function load(){if(mode==='demo')return;setLoading(true);try{const r=await fetch(`/api/app/data?date=${today}`,{cache:'no-store'});if(r.status===401){router.push('/masuk');return}const j=await r.json();if(!r.ok)throw new Error(j.message);setData(j)}catch(e:any){flash(e.message||'Data belum dapat dimuat.')}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  useEffect(()=>{const map:Record<string,string>={};data.students.forEach(s=>map[s.id]='Hadir');data.attendance.forEach(a=>map[a.student_id]=a.status);setAttendanceMap(map)},[data.students,data.attendance]);
  function flash(m:string){setToast(m);setTimeout(()=>setToast(''),2200)}
  function open(type:ModalType,student?:Student){setSelected(student||null);setModal(type)}
  async function logout(){if(mode==='demo'){router.push('/');return}await fetch('/api/keluar',{method:'POST'});router.push('/masuk');router.refresh()}

  const counts=useMemo(()=>{const vals=Object.values(attendanceMap);return {hadir:vals.filter(x=>x==='Hadir').length,tidak:vals.filter(x=>x!=='Hadir').length,alfa:vals.filter(x=>x==='Alfa').length,terlambat:vals.filter(x=>x==='Terlambat').length}},[attendanceMap]);
  const attention=useMemo(()=>{const ids=new Set<string>();data.notes.filter(n=>String(n.status).includes('Tindak')||String(n.status).includes('Perlu')).forEach(n=>ids.add(n.student_id));data.attendance.filter(a=>['Alfa','Terlambat'].includes(a.status)).forEach(a=>ids.add(a.student_id));return data.students.filter(s=>ids.has(s.id)).slice(0,5)},[data]);
  const filteredStudents=data.students.filter(s=>`${s.name} ${s.nis||''} ${s.nisn||''} ${s.guardian_name||''}`.toLowerCase().includes(search.toLowerCase()));

  async function saveAttendance(){const records=data.students.map(s=>({student_id:s.id,status:attendanceMap[s.id]||'Hadir',note:''}));if(mode==='demo'){setData(d=>({...d,attendance:records}));flash('Kehadiran demo berhasil disimpan.');return}const r=await fetch('/api/kehadiran',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({date:today,records})});const j=await r.json();if(!r.ok)return flash(j.message);flash('Kehadiran berhasil disimpan.');load()}

  async function createFromForm(e:React.FormEvent<HTMLFormElement>,type:Exclude<ModalType,'detail'|null>){e.preventDefault();const fd=new FormData(e.currentTarget);const body:any=Object.fromEntries(fd.entries());if(mode==='demo'){const student=data.students.find(s=>s.id===body.student_id);const id=`demo-${Date.now()}`;setData(d=>{
      if(type==='siswa')return {...d,students:[...d.students,{id,name:body.name,nis:body.nis,nisn:body.nisn,gender:body.gender,guardian_name:body.guardian_name,guardian_phone:body.guardian_phone,status:'Aktif'}]};
      if(type==='catatan')return {...d,notes:[{id,student_id:body.student_id,student_name:student?.name,category:body.category,title:body.title,content:body.content,status:body.status,occurred_at:new Date().toISOString()},...d.notes]};
      if(type==='prestasi')return {...d,achievements:[{id,student_id:body.student_id,student_name:student?.name,title:body.title,category:body.category,level:body.level,achieved_at:body.achieved_at||today},...d.achievements]};
      if(type==='tindak')return {...d,followUps:[{id,student_id:body.student_id,student_name:student?.name||'Umum',title:body.title,action:body.action,due_date:body.due_date,status:'Belum Dimulai'},...d.followUps]};
      if(type==='agenda')return {...d,agendas:[...d.agendas,{id,title:body.title,category:body.category,agenda_date:body.agenda_date,agenda_time:body.agenda_time,description:body.description,is_done:false}]};
      if(type==='komunikasi')return {...d,communications:[{id,student_id:body.student_id,student_name:student?.name,method:body.method,topic:body.topic,result:body.result,communicated_at:new Date().toISOString()},...d.communications]};
      return d;
    });setModal(null);flash('Data demo berhasil ditambahkan.');return}
    const endpoint:{[k:string]:string}={siswa:'/api/siswa',catatan:'/api/catatan',prestasi:'/api/prestasi',tindak:'/api/tindak-lanjut',agenda:'/api/agenda',komunikasi:'/api/komunikasi'};
    const r=await fetch(endpoint[type],{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)return flash(j.message||'Data belum berhasil disimpan.');setModal(null);flash('Data berhasil disimpan.');load();
  }
  async function completeFollow(id:string){if(mode==='demo'){setData(d=>({...d,followUps:d.followUps.map(f=>f.id===id?{...f,status:'Selesai'}:f)}));flash('Tindak lanjut ditandai selesai.');return}await fetch('/api/tindak-lanjut',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status:'Selesai',result:'Selesai ditindaklanjuti.'})});flash('Tindak lanjut selesai.');load()}

  const profile=data.profile||{};
  const titles:Record<View,[string,string]>={beranda:['Beranda','Ringkasan kelas dan pekerjaan penting hari ini.'],siswa:['Siswa','Data siswa dalam satu ruang yang mudah dicari.'],kehadiran:['Kehadiran','Catat kehadiran hari ini dengan cepat.'],catatan:['Catatan Wali Kelas','Dokumentasikan perkembangan dan hal penting siswa.'],prestasi:['Prestasi','Catat kemajuan dan pencapaian positif siswa.'],tindak:['Tindak Lanjut','Pastikan setiap hal penting benar-benar ditindaklanjuti.'],orangtua:['Orang Tua','Kontak dan riwayat komunikasi dengan orang tua/wali.'],agenda:['Agenda Kelas','Kegiatan, rapat, dan jadwal penting kelas.'],laporan:['Laporan','Ringkasan kelas yang siap dicetak atau direkap.'],pengaturan:['Pengaturan','Informasi lisensi dan profil kelas.']};

  function pageAction(){if(view==='siswa')return <button className="btn btn-primary" onClick={()=>open('siswa')}><Plus size={16}/>Tambah Siswa</button>;if(view==='catatan')return <button className="btn btn-primary" onClick={()=>open('catatan')}><Plus size={16}/>Tambah Catatan</button>;if(view==='prestasi')return <button className="btn btn-primary" onClick={()=>open('prestasi')}><Plus size={16}/>Tambah Prestasi</button>;if(view==='tindak')return <button className="btn btn-primary" onClick={()=>open('tindak')}><Plus size={16}/>Tambah Tindak Lanjut</button>;if(view==='agenda')return <button className="btn btn-primary" onClick={()=>open('agenda')}><Plus size={16}/>Tambah Agenda</button>;if(view==='orangtua')return <button className="btn btn-primary" onClick={()=>open('komunikasi')}><Plus size={16}/>Catat Komunikasi</button>;return null}

  const Beranda=()=> <>
    <div className="stats-grid">
      <Stat icon={<UsersRound size={19}/>} value={data.students.length} label="Siswa aktif"/>
      <Stat icon={<Check size={19}/>} value={counts.hadir} label="Hadir hari ini"/>
      <Stat icon={<ShieldAlert size={19}/>} value={attention.length} label="Perlu perhatian"/>
      <Stat icon={<Activity size={19}/>} value={data.followUps.filter(f=>f.status!=='Selesai').length} label="Tindak lanjut aktif"/>
    </div>
    <div className="grid-2">
      <div className="card"><div className="card-head"><div><h3>Perlu perhatian hari ini</h3><div className="subtle">Hal yang sebaiknya tidak terlewat.</div></div><Bell size={18}/></div>
        {attention.length===0?<div className="empty">Belum ada siswa yang membutuhkan perhatian khusus hari ini.</div>:<div className="attention-list">{attention.map(s=>{const att=data.attendance.find(a=>a.student_id===s.id);const note=data.notes.find(n=>n.student_id===s.id&&String(n.status).includes('Tindak'));return <div className="attention-row" key={s.id}><div className="avatar">{initials(s.name)}</div><div className="row-main"><b>{s.name}</b><small>{note?.title||(`${att?.status||'Perlu'} · perlu dipantau`)}</small></div><button className="btn btn-ghost" style={{padding:'8px 10px'}} onClick={()=>open('detail',s)}>Lihat</button></div>})}</div>}
      </div>
      <div className="card"><div className="card-head"><div><h3>Agenda terdekat</h3><div className="subtle">Jadwal kelas yang akan datang.</div></div><CalendarDays size={18}/></div><div className="agenda-list">{data.agendas.slice(0,4).map(a=><div className="agenda-row" key={a.id}><div className="time-box">{a.agenda_time?String(a.agenda_time).slice(0,5):'Hari ini'}</div><div><b style={{fontSize:13}}>{a.title}</b><div className="subtle">{indoDate(a.agenda_date)} · {a.category}</div></div></div>)}{!data.agendas.length&&<div className="empty">Belum ada agenda.</div>}</div></div>
    </div>
    <div className="card" style={{marginTop:16}}><div className="card-head"><div><h3>Aksi cepat</h3><div className="subtle">Catat hal penting tanpa mencari menu.</div></div></div><div style={{display:'flex',gap:9,flexWrap:'wrap'}}><button className="btn btn-soft" onClick={()=>setView('kehadiran')}><ClipboardCheck size={16}/>Ambil Kehadiran</button><button className="btn btn-ghost" onClick={()=>open('catatan')}><NotebookPen size={16}/>Catatan Siswa</button><button className="btn btn-ghost" onClick={()=>open('tindak')}><Activity size={16}/>Tindak Lanjut</button><button className="btn btn-ghost" onClick={()=>open('agenda')}><CalendarDays size={16}/>Agenda Baru</button></div></div>
  </>;

  const Siswa=()=> <><div className="search-row"><div className="search-box"><Search size={17}/><input className="input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari nama, NIS, NISN, atau orang tua..."/></div><span className="pill">{filteredStudents.length} siswa</span></div><div className="student-grid">{filteredStudents.map(s=><article className="student-card" key={s.id} onClick={()=>open('detail',s)}><div className="student-top"><div className="avatar">{initials(s.name)}</div><div><b>{s.name}</b><div className="subtle">NIS {s.nis||'-'} · {s.gender||'Data belum lengkap'}</div></div></div><div className="student-meta"><span className="badge badge-good">{s.status||'Aktif'}</span>{data.notes.some(n=>n.student_id===s.id&&String(n.status).includes('Tindak'))&&<span className="badge badge-warn">Perlu tindak lanjut</span>}</div></article>)}{!filteredStudents.length&&<div className="empty">Siswa tidak ditemukan.</div>}</div></>;

  const Kehadiran=()=> <div className="card"><div className="card-head"><div><h3>Kehadiran {indoDate(today)}</h3><div className="subtle">Semua siswa otomatis ditandai Hadir. Ubah hanya yang berbeda.</div></div><span className="badge badge-info">{counts.hadir}/{data.students.length} hadir</span></div>{data.students.length===0?<div className="empty">Tambahkan siswa terlebih dahulu.</div>:<div className="attendance-list">{data.students.map(s=><div className="attendance-row" key={s.id}><div className="student-top"><div className="avatar">{initials(s.name)}</div><div><b>{s.name}</b><div className="subtle">NIS {s.nis||'-'}</div></div></div><select className="input" value={attendanceMap[s.id]||'Hadir'} onChange={e=>setAttendanceMap(m=>({...m,[s.id]:e.target.value}))}><option>Hadir</option><option>Sakit</option><option>Izin</option><option>Alfa</option><option>Terlambat</option><option>Dispensasi</option></select></div>)}</div>}<div style={{display:'flex',justifyContent:'flex-end',marginTop:16}}><button className="btn btn-primary" onClick={saveAttendance}><Check size={17}/>Simpan Kehadiran</button></div></div>;

  const Catatan=()=> <ListTable headers={['Siswa','Kategori','Catatan','Status','Tanggal']} rows={data.notes.map(n=>[n.student_name,n.category,<><strong>{n.title}</strong><br/><small className="subtle">{n.content}</small></>,<span className={`badge ${statusClass(n.status)}`}>{n.status}</span>,indoDate(n.occurred_at)])} empty="Belum ada catatan wali kelas."/>;
  const Prestasi=()=> <ListTable headers={['Siswa','Prestasi','Kategori','Tingkat','Tanggal']} rows={data.achievements.map(a=>[a.student_name,<><strong>{a.title}</strong>{a.rank&&<><br/><small className="subtle">{a.rank}</small></>}</>,a.category,a.level||'-',indoDate(a.achieved_at)])} empty="Belum ada prestasi yang dicatat."/>;
  const Tindak=()=> <div className="attention-list">{data.followUps.map(f=><div className="card" key={f.id} style={{padding:16}}><div style={{display:'flex',gap:12,alignItems:'flex-start'}}><div className="avatar"><Activity size={18}/></div><div className="row-main"><div style={{display:'flex',gap:8,flexWrap:'wrap',alignItems:'center'}}><b>{f.title}</b><span className={`badge ${statusClass(f.status)}`}>{f.status}</span></div><div className="subtle" style={{marginTop:4}}>{f.student_name} · Target {indoDate(f.due_date)}</div><p style={{margin:'10px 0 0',fontSize:13}}>{f.action}</p></div>{f.status!=='Selesai'&&<button className="btn btn-ghost" onClick={()=>completeFollow(f.id)}><Check size={15}/>Selesai</button>}</div></div>)}{!data.followUps.length&&<div className="empty">Belum ada tindak lanjut.</div>}</div>;
  const OrangTua=()=> <><div className="student-grid">{data.students.map(s=><article className="student-card" key={s.id}><div className="student-top"><div className="avatar">{initials(s.name)}</div><div><b>{s.name}</b><div className="subtle">{s.guardian_name||'Orang tua belum diisi'}</div></div></div><div style={{marginTop:14,display:'flex',gap:8}}>{s.guardian_phone?<a className="btn btn-soft" style={{flex:1}} target="_blank" href={`https://wa.me/${String(s.guardian_phone).replace(/\D/g,'').replace(/^0/,'62')}`}><MessageCircle size={15}/>WhatsApp</a>:<span className="subtle">Nomor belum tersedia.</span>}</div></article>)}</div><div className="card" style={{marginTop:18}}><div className="card-head"><h3>Riwayat komunikasi</h3></div>{data.communications.length?<div className="agenda-list">{data.communications.map(c=><div className="agenda-row" key={c.id}><div className="time-box">{c.method}</div><div><b>{c.student_name} · {c.topic}</b><div className="subtle">{c.result||'Tidak ada catatan hasil'} · {indoDate(c.communicated_at)}</div></div></div>)}</div>:<div className="empty">Belum ada komunikasi yang dicatat.</div>}</div></>;
  const Agenda=()=> <div className="card"><div className="agenda-list">{data.agendas.map(a=><div className="agenda-row" key={a.id}><div className="time-box"><Clock3 size={14}/><br/>{a.agenda_time?String(a.agenda_time).slice(0,5):'—'}</div><div className="row-main"><b>{a.title}</b><div className="subtle">{indoDate(a.agenda_date)} · {a.category}</div>{a.description&&<p style={{fontSize:13,margin:'7px 0 0'}}>{a.description}</p>}</div><span className={`badge ${a.is_done?'badge-good':'badge-info'}`}>{a.is_done?'Selesai':'Terjadwal'}</span></div>)}{!data.agendas.length&&<div className="empty">Belum ada agenda kelas.</div>}</div></div>;
  const Laporan=()=> <div className="report-grid"><Report title="Ringkasan Kelas" desc={`${data.students.length} siswa · ${counts.hadir} hadir hari ini`} onClick={()=>window.print()}/><Report title="Rekap Kehadiran Hari Ini" desc={`${counts.tidak} siswa tidak berstatus Hadir`} onClick={()=>window.print()}/><Report title="Catatan & Tindak Lanjut" desc={`${data.notes.length} catatan · ${data.followUps.filter(f=>f.status!=='Selesai').length} aktif`} onClick={()=>window.print()}/><Report title="Prestasi Siswa" desc={`${data.achievements.length} prestasi telah didokumentasikan`} onClick={()=>window.print()}/></div>;
  const Pengaturan=()=> <div className="grid-2"><div className="card"><div className="card-head"><h3>Profil Kelas</h3><GraduationCap/></div><div className="field"><label>Wali Kelas</label><div className="input">{profile.teacher_name||'-'}</div></div><div className="field"><label>Sekolah</label><div className="input">{profile.school_name||'-'}</div></div><div className="field"><label>Kelas</label><div className="input">{profile.class_name||'-'}</div></div><div className="field"><label>Tahun Ajaran</label><div className="input">{profile.academic_year||'-'}</div></div></div><div className="card"><div className="card-head"><h3>Lisensi</h3><BookOpenCheck/></div><p className="subtle">Kode lisensi</p><div className="code-box">{profile.code||'MODE-DEMO'}</div><p className="subtle" style={{marginTop:16}}>{mode==='demo'?'Mode Demo menggunakan data lokal dan tidak menyimpan data ke database.':'Data pada lisensi ini terpisah dari pengguna lain.'}</p><button className="btn btn-danger" onClick={logout} style={{marginTop:15}}><LogOut size={16}/>{mode==='demo'?'Keluar dari Demo':'Keluar dari Akun'}</button></div></div>;

  const page={beranda:<Beranda/>,siswa:<Siswa/>,kehadiran:<Kehadiran/>,catatan:<Catatan/>,prestasi:<Prestasi/>,tindak:<Tindak/>,orangtua:<OrangTua/>,agenda:<Agenda/>,laporan:<Laporan/>,pengaturan:<Pengaturan/>}[view];
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark" style={{background:'rgba(255,255,255,.11)'}}>K</span>KelasKita</div><div className="side-class"><b>{profile.class_name||'Kelas'}</b><small style={{display:'block',marginTop:4}}>{profile.school_name||'Sekolah'} · {profile.academic_year||''}</small></div><nav className="side-nav">{nav.map(([k,l,I])=><button key={k} className={view===k?'active':''} onClick={()=>setView(k)}><I size={17}/>{l}</button>)}</nav><div className="sidebar-foot"><button className="btn" style={{width:'100%',background:'rgba(255,255,255,.08)',color:'#dbe2f5'}} onClick={logout}><LogOut size={15}/>{mode==='demo'?'Keluar Demo':'Keluar'}</button></div></aside>
    <main className="app-main"><header className="topbar"><div className="topbar-left"><b>{profile.teacher_name||'Wali Kelas'}</b><small>{profile.class_name||'Kelas'} · {profile.academic_year||''}</small></div><div className="top-actions"><button className="icon-btn hide-mobile"><Search size={17}/></button><button className="icon-btn"><Bell size={17}/></button><div className="avatar">{initials(profile.teacher_name||'WK')}</div></div></header><div className="app-content">{mode==='demo'&&<div className="demo-banner"><span><Sparkles size={15} style={{verticalAlign:'middle',marginRight:7}}/><b>Mode Demo.</b> Silakan mencoba fitur. Semua perubahan hanya tersimpan sementara di sesi demo ini.</span><button className="btn btn-ghost" style={{padding:'7px 10px'}} onClick={()=>router.push('/masuk')}>Punya lisensi? Masuk</button></div>}<div className="page-head"><div><h1>{titles[view][0]}</h1><p>{titles[view][1]}</p></div>{pageAction()}</div>{loading?<div className="card"><div className="empty">Menyiapkan ruang kelas...</div></div>:page}</div></main>
    <nav className="mobile-nav">{(['beranda','siswa','kehadiran','agenda'] as View[]).map(k=>{const x=nav.find(n=>n[0]===k)!;const I=x[2];return <button key={k} className={view===k?'active':''} onClick={()=>{setView(k);setMoreOpen(false)}}><I size={19}/>{x[1]}</button>})}<button className={moreOpen||['catatan','prestasi','tindak','orangtua','laporan','pengaturan'].includes(view)?'active':''} onClick={()=>setMoreOpen(v=>!v)}><Menu size={19}/>Lainnya</button></nav>
    {moreOpen&&<div className="mobile-more"><div className="mobile-more-grid">{(['catatan','prestasi','tindak','orangtua','laporan','pengaturan'] as View[]).map(k=>{const x=nav.find(n=>n[0]===k)!;const I=x[2];return <button key={k} onClick={()=>{setView(k);setMoreOpen(false)}}><span><I size={18}/></span>{x[1]}</button>})}</div></div>}
    <button className="fab" onClick={()=>open('catatan')} aria-label="Tambah cepat"><Plus/></button>
    {modal&&<Modal type={modal} selected={selected} students={data.students} today={today} close={()=>setModal(null)} submit={createFromForm} data={data}/>} {toast&&<div className="toast">{toast}</div>}
  </div>
}

function Stat({icon,value,label}:{icon:React.ReactNode;value:number;label:string}){return <div className="stat-card"><div className="stat-icon">{icon}</div><h3>{value}</h3><p>{label}</p></div>}
function ListTable({headers,rows,empty}:{headers:string[];rows:React.ReactNode[][];empty:string}){return rows.length?<div className="table-wrap"><table className="table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>:<div className="card"><div className="empty">{empty}</div></div>}
function Report({title,desc,onClick}:{title:string;desc:string;onClick:()=>void}){return <div className="report-card"><div className="stat-icon"><FileText size={18}/></div><h3>{title}</h3><p className="subtle">{desc}</p><button className="btn btn-ghost" onClick={onClick}>Cetak / Simpan PDF <ChevronRight size={15}/></button></div>}

function Modal({type,selected,students,today,close,submit,data}:{type:ModalType;selected:Student|null;students:Student[];today:string;close:()=>void;submit:(e:React.FormEvent<HTMLFormElement>,t:any)=>void;data:DataShape}){
  if(type==='detail'&&selected){const notes=data.notes.filter(n=>n.student_id===selected.id);const achievements=data.achievements.filter(a=>a.student_id===selected.id);const follow=data.followUps.filter(f=>f.student_id===selected.id);return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal"><div className="modal-head"><div className="student-top"><div className="avatar">{initials(selected.name)}</div><div><h2>{selected.name}</h2><div className="subtle">NIS {selected.nis||'-'} · NISN {selected.nisn||'-'}</div></div></div><button className="icon-btn" onClick={close}><X size={18}/></button></div><div className="stats-grid" style={{gridTemplateColumns:'repeat(3,1fr)',margin:'18px 0'}}><div className="stat-card"><p>Catatan</p><h3>{notes.length}</h3></div><div className="stat-card"><p>Prestasi</p><h3>{achievements.length}</h3></div><div className="stat-card"><p>Tindak lanjut</p><h3>{follow.filter(f=>f.status!=='Selesai').length}</h3></div></div><div className="card" style={{boxShadow:'none'}}><div className="card-head"><h3>Orang Tua/Wali</h3></div><b>{selected.guardian_name||'Belum diisi'}</b><div className="subtle">{selected.guardian_phone||'Nomor belum diisi'}</div></div>{notes.slice(0,3).map(n=><div className="attention-row" key={n.id}><div className="row-main"><b>{n.title}</b><small>{n.category} · {indoDate(n.occurred_at)}</small></div><span className={`badge ${statusClass(n.status)}`}>{n.status}</span></div>)}</div></div>}
  const studentSelect=<div className="field"><label>Siswa</label><select className="input" name="student_id" defaultValue={selected?.id||''} required><option value="">Pilih siswa</option>{students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div>;
  let title='Tambah Data'; let body:React.ReactNode=null;
  if(type==='siswa'){title='Tambah Siswa';body=<><div className="quick-form"><div className="field full"><label>Nama Lengkap</label><input className="input" name="name" required/></div><div className="field"><label>NIS</label><input className="input" name="nis"/></div><div className="field"><label>NISN</label><input className="input" name="nisn"/></div><div className="field"><label>Jenis Kelamin</label><select className="input" name="gender"><option value="">Pilih</option><option>Laki-laki</option><option>Perempuan</option></select></div><div className="field"><label>Nama Orang Tua/Wali</label><input className="input" name="guardian_name"/></div><div className="field full"><label>Nomor WhatsApp Orang Tua</label><input className="input" name="guardian_phone" inputMode="tel"/></div></div></>}
  if(type==='catatan'){title='Tambah Catatan Wali Kelas';body=<>{studentSelect}<div className="quick-form"><div className="field"><label>Kategori</label><select className="input" name="category"><option>Umum</option><option>Akademik</option><option>Kehadiran</option><option>Sikap</option><option>Kedisiplinan</option><option>Sosial</option><option>Orang Tua</option><option>Prestasi</option></select></div><div className="field"><label>Status</label><select className="input" name="status"><option>Informasi</option><option>Perlu Perhatian</option><option>Perlu Tindak Lanjut</option><option>Selesai</option></select></div><div className="field full"><label>Judul</label><input className="input" name="title" required/></div><div className="field full"><label>Isi Catatan</label><textarea className="input" name="content" rows={5} required/></div></div></>}
  if(type==='prestasi'){title='Tambah Prestasi';body=<>{studentSelect}<div className="quick-form"><div className="field full"><label>Nama Prestasi</label><input className="input" name="title" required/></div><div className="field"><label>Kategori</label><select className="input" name="category"><option>Akademik</option><option>Seni</option><option>Olahraga</option><option>Organisasi</option><option>Keagamaan</option><option>Teknologi</option><option>Lainnya</option></select></div><div className="field"><label>Tingkat</label><select className="input" name="level"><option>Sekolah</option><option>Kecamatan</option><option>Kota/Kabupaten</option><option>Provinsi</option><option>Nasional</option><option>Internasional</option></select></div><div className="field full"><label>Tanggal</label><input className="input" type="date" name="achieved_at" defaultValue={today}/></div></div></>}
  if(type==='tindak'){title='Tambah Tindak Lanjut';body=<>{studentSelect}<div className="field"><label>Judul</label><input className="input" name="title" required/></div><div className="field"><label>Tindakan yang perlu dilakukan</label><textarea className="input" name="action" rows={4} required/></div><div className="field"><label>Tanggal Target</label><input className="input" name="due_date" type="date" defaultValue={today}/></div></>}
  if(type==='agenda'){title='Tambah Agenda';body=<><div className="field"><label>Nama Agenda</label><input className="input" name="title" required/></div><div className="quick-form"><div className="field"><label>Kategori</label><select className="input" name="category"><option>Kegiatan</option><option>Akademik</option><option>Kelas</option><option>Orang Tua</option><option>Rapat</option><option>Lomba</option></select></div><div className="field"><label>Tanggal</label><input className="input" name="agenda_date" type="date" defaultValue={today} required/></div><div className="field"><label>Waktu</label><input className="input" name="agenda_time" type="time"/></div><div className="field full"><label>Keterangan</label><textarea className="input" name="description" rows={3}/></div></div></>}
  if(type==='komunikasi'){title='Catat Komunikasi Orang Tua';body=<>{studentSelect}<div className="quick-form"><div className="field"><label>Metode</label><select className="input" name="method"><option>WhatsApp</option><option>Telepon</option><option>Tatap Muka</option><option>Surat</option><option>Lainnya</option></select></div><div className="field"><label>Topik</label><input className="input" name="topic" required/></div><div className="field full"><label>Hasil Komunikasi</label><textarea className="input" name="result" rows={4}/></div></div></>}
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><form className="modal" onSubmit={e=>submit(e,type as any)}><div className="modal-head"><h2>{title}</h2><button type="button" className="icon-btn" onClick={close}><X size={18}/></button></div>{body}<div className="modal-actions"><button type="button" className="btn btn-ghost" onClick={close}>Batal</button><button className="btn btn-primary">Simpan</button></div></form></div>
}
