'use client';

import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import {
  Activity, BookOpen, CalendarDays, Check, ChevronRight, ClipboardCheck, Clock3,
  Download, FileText, House, LogOut, Menu, MessageCircle, MoreHorizontal,
  NotebookPen, Pencil, Plus, Search, Settings, Trash2, Trophy, UsersRound, X
} from 'lucide-react';
import Brand from '@/components/Brand';
import { demoData } from '@/lib/demo-data';

type Mode='demo'|'real';
type Student={id:string;nis?:string;nisn?:string;name:string;gender?:string;birth_place?:string;birth_date?:string;guardian_name?:string;guardian_phone?:string;phone?:string;address?:string;status?:string};
type Subject={id:string;name:string;teacher_name?:string;mastery_score:number|string;is_active?:boolean};
type Schedule={id:string;subject_id:string;subject_name:string;teacher_name?:string;day_name:string;start_time:string;end_time:string;room?:string};
type Assessment={id:string;subject_id:string;subject_name:string;name:string;category:string;semester:string;assessment_date:string;max_score:number|string};
type Score={id?:string;assessment_id:string;student_id:string;score?:number|null;remedial_score?:number|null;note?:string};
type AcademicSettings={active_semester:string;calculation_mode:string;daily_weight:number|string;quiz_weight:number|string;semester_weight:number|string};
type DataShape={profile:any;students:Student[];attendance:any[];notes:any[];achievements:any[];followUps:any[];communications:any[];agendas:any[];subjects:Subject[];schedules:Schedule[];assessments:Assessment[];scores:Score[];academicSettings:AcademicSettings};
type View='beranda'|'siswa'|'kehadiran'|'akademik'|'jadwal'|'catatan'|'prestasi'|'tindak'|'orangtua'|'agenda'|'laporan'|'pengaturan';
type ModalType='siswa'|'catatan'|'prestasi'|'tindak'|'agenda'|'komunikasi'|'detail'|'mapel'|'penilaian'|'jadwal'|'nilai'|null;

const nav=[
  ['beranda','Beranda',House],['siswa','Siswa',UsersRound],['kehadiran','Kehadiran',ClipboardCheck],
  ['akademik','Akademik',BookOpen],['jadwal','Jadwal Pelajaran',CalendarDays],['catatan','Catatan',NotebookPen],
  ['prestasi','Prestasi',Trophy],['tindak','Tindak Lanjut',Activity],['orangtua','Orang Tua',MessageCircle],
  ['agenda','Agenda',CalendarDays],['laporan','Laporan',FileText],['pengaturan','Pengaturan',Settings]
] as const;
const dayOrder=['Senin','Selasa','Rabu','Kamis','Jumat','Sabtu','Minggu'];
const categories=['Tugas Harian','Ulangan Harian','Tengah Semester','Akhir Semester','Lainnya'];

function localDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function indoDate(v?:string){if(!v)return '-';const d=new Date(v.length===10?`${v}T00:00:00`:v);return d.toLocaleDateString('id-ID',{day:'numeric',month:'short',year:'numeric'})}
function initials(name:string){return name.split(' ').slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function statusClass(status:string){if(/Selesai|Hadir|Aman|Aktif|Tuntas/.test(status))return'badge-good';if(/Alfa|Butuh|Nonaktif/.test(status))return'badge-danger';if(/Perlu|Belum|Terlambat|Menunggu/.test(status))return'badge-warn';return'badge-info'}
function n(v:any){const x=Number(v);return Number.isFinite(x)?x:0}
function scoreUsed(s?:Score|null){if(!s)return null;return s.remedial_score!==null&&s.remedial_score!==undefined?n(s.remedial_score):s.score!==null&&s.score!==undefined?n(s.score):null}
function dayToday(){const d=new Date().toLocaleDateString('id-ID',{weekday:'long'});return d.charAt(0).toUpperCase()+d.slice(1)}

export default function KelasKitaApp({mode}:{mode:Mode}){
  const router=useRouter();
  const [data,setData]=useState<DataShape>(()=>JSON.parse(JSON.stringify(demoData)));
  const [view,setView]=useState<View>('beranda');
  const [loading,setLoading]=useState(mode==='real');
  const [search,setSearch]=useState('');
  const [modal,setModal]=useState<ModalType>(null);
  const [selected,setSelected]=useState<any>(null);
  const [toast,setToast]=useState('');
  const [moreOpen,setMoreOpen]=useState(false);
  const [attendanceMap,setAttendanceMap]=useState<Record<string,string>>({});
  const [academicTab,setAcademicTab]=useState<'mapel'|'penilaian'|'remedial'>('mapel');
  const [selectedSubject,setSelectedSubject]=useState<string>('');
  const [scoreDraft,setScoreDraft]=useState<Record<string,{score:string;remedial:string;note:string}>>({});
  const [reportMonth,setReportMonth]=useState(new Date().toISOString().slice(0,7));
  const today=localDate();

  async function load(){if(mode==='demo')return;setLoading(true);try{const r=await fetch(`/api/app/data?date=${today}`,{cache:'no-store'});if(r.status===401){router.push('/masuk');return}const j=await r.json();if(!r.ok)throw new Error(j.message);setData(j)}catch(e:any){flash(e.message||'Data belum dapat dimuat.')}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  useEffect(()=>{const map:Record<string,string>={};data.students.forEach(s=>map[s.id]='Hadir');data.attendance.forEach(a=>map[a.student_id]=a.status);setAttendanceMap(map)},[data.students,data.attendance]);
  useEffect(()=>{if(data.subjects?.length&&(!selectedSubject||!data.subjects.some(s=>s.id===selectedSubject)))setSelectedSubject(data.subjects[0].id);if(!data.subjects?.length&&selectedSubject)setSelectedSubject('')},[data.subjects,selectedSubject]);

  function flash(m:string){setToast(m);window.setTimeout(()=>setToast(''),2300)}
  function open(type:ModalType,item?:any){setSelected(item||null);setModal(type)}
  function close(){setModal(null);setSelected(null);setScoreDraft({})}
  async function logout(){if(mode==='demo'){router.push('/');return}await fetch('/api/keluar',{method:'POST'});router.push('/masuk');router.refresh()}
  async function api(endpoint:string,method:string,body:any){const r=await fetch(endpoint,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||'Permintaan belum berhasil.');return j}

  const counts=useMemo(()=>{const vals=Object.values(attendanceMap);return {hadir:vals.filter(x=>x==='Hadir').length,tidak:vals.filter(x=>x!=='Hadir').length,alfa:vals.filter(x=>x==='Alfa').length,terlambat:vals.filter(x=>x==='Terlambat').length}},[attendanceMap]);
  const filteredStudents=data.students.filter(s=>`${s.name} ${s.nis||''} ${s.nisn||''} ${s.guardian_name||''}`.toLowerCase().includes(search.toLowerCase()));
  const todaySchedules=useMemo(()=>data.schedules.filter(s=>s.day_name===dayToday()),[data.schedules]);

  function normalizedScore(sc:Score,assessment:Assessment){const used=scoreUsed(sc);if(used===null)return null;const max=Math.max(1,n(assessment.max_score)||100);return Math.min(100,(used/max)*100)}
  function subjectFinal(studentId:string,subjectId:string){const aset=data.assessments.filter(a=>a.subject_id===subjectId&&a.semester===data.academicSettings.active_semester);const vals=aset.map(a=>{const sc=data.scores.find(s=>s.assessment_id===a.id&&s.student_id===studentId);const v=sc?normalizedScore(sc,a):null;return v===null?null:{category:a.category,value:v}}).filter(Boolean) as {category:string;value:number}[];if(!vals.length)return null;if(data.academicSettings.calculation_mode!=='Otomatis')return vals.reduce((x,y)=>x+y.value,0)/vals.length;const avg=(cats:string[])=>{const x=vals.filter(v=>cats.includes(v.category));return x.length?x.reduce((a,b)=>a+b.value,0)/x.length:null};const daily=avg(['Tugas Harian']),quiz=avg(['Ulangan Harian']),sem=avg(['Tengah Semester','Akhir Semester','Lainnya']);let total=0,weight=0;[[daily,n(data.academicSettings.daily_weight)],[quiz,n(data.academicSettings.quiz_weight)],[sem,n(data.academicSettings.semester_weight)]].forEach(([v,w]:any)=>{if(v!==null&&w>0){total+=v*w;weight+=w}});return weight?total/weight:null}
  function studentAcademicWarnings(studentId:string){return data.subjects.filter(s=>{const v=subjectFinal(studentId,s.id);return v!==null&&v<n(s.mastery_score)}).length}
  const attention=useMemo(()=>{const ids=new Set<string>();data.notes.filter(n=>String(n.status).includes('Tindak')||String(n.status).includes('Perlu')).forEach(n=>ids.add(n.student_id));data.attendance.filter(a=>['Alfa','Terlambat'].includes(a.status)).forEach(a=>ids.add(a.student_id));data.students.forEach(st=>{if(studentAcademicWarnings(st.id)>0)ids.add(st.id)});return data.students.filter(s=>ids.has(s.id)).slice(0,6)},[data]);
  const classAverage=useMemo(()=>{const vals:number[]=[];data.students.forEach(st=>data.subjects.forEach(sb=>{const v=subjectFinal(st.id,sb.id);if(v!==null)vals.push(v)}));return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null},[data]);

  async function importStudents(file:File){if(mode==='demo'){flash('Impor Excel tersedia pada akun berlisensi.');return}const form=new FormData();form.append('file',file);try{const r=await fetch('/api/siswa/import',{method:'POST',body:form});const j=await r.json();if(!r.ok)throw new Error(j.message);flash(`${j.inserted} siswa berhasil diimpor${j.skipped?`, ${j.skipped} dilewati`:''}.`);load()}catch(e:any){flash(e.message||'Impor belum berhasil.')}}

  async function saveAttendance(){const records=data.students.map(s=>({student_id:s.id,status:attendanceMap[s.id]||'Hadir',note:''}));if(mode==='demo'){setData(d=>({...d,attendance:records}));flash('Kehadiran demo berhasil disimpan.');return}try{await api('/api/kehadiran','POST',{date:today,records});flash('Kehadiran berhasil disimpan.');load()}catch(e:any){flash(e.message)}}

  async function createBasic(e:React.FormEvent<HTMLFormElement>,type:Exclude<ModalType,'detail'|'mapel'|'penilaian'|'jadwal'|'nilai'|null>){e.preventDefault();const body:any=Object.fromEntries(new FormData(e.currentTarget).entries());if(mode==='demo'){const student=data.students.find(s=>s.id===body.student_id);const id=`demo-${Date.now()}`;setData(d=>{if(type==='siswa')return {...d,students:[...d.students,{id,name:body.name,nis:body.nis,nisn:body.nisn,gender:body.gender,guardian_name:body.guardian_name,guardian_phone:body.guardian_phone,status:'Aktif'}]};if(type==='catatan')return {...d,notes:[{id,student_id:body.student_id,student_name:student?.name,category:body.category,title:body.title,content:body.content,status:body.status,occurred_at:new Date().toISOString()},...d.notes]};if(type==='prestasi')return {...d,achievements:[{id,student_id:body.student_id,student_name:student?.name,title:body.title,category:body.category,level:body.level,achieved_at:body.achieved_at||today},...d.achievements]};if(type==='tindak')return {...d,followUps:[{id,student_id:body.student_id,student_name:student?.name||'Umum',title:body.title,action:body.action,due_date:body.due_date,status:'Belum Dimulai'},...d.followUps]};if(type==='agenda')return {...d,agendas:[...d.agendas,{id,title:body.title,category:body.category,agenda_date:body.agenda_date,agenda_time:body.agenda_time,description:body.description,is_done:false}]};if(type==='komunikasi')return {...d,communications:[{id,student_id:body.student_id,student_name:student?.name,method:body.method,topic:body.topic,result:body.result,communicated_at:new Date().toISOString()},...d.communications]};return d});close();flash('Data demo berhasil ditambahkan.');return}
    const endpoint:{[k:string]:string}={siswa:'/api/siswa',catatan:'/api/catatan',prestasi:'/api/prestasi',tindak:'/api/tindak-lanjut',agenda:'/api/agenda',komunikasi:'/api/komunikasi'};try{await api(endpoint[type],'POST',body);close();flash('Data berhasil disimpan.');load()}catch(e:any){flash(e.message)}}

  async function saveStudent(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const body:any=Object.fromEntries(new FormData(e.currentTarget).entries());if(!selected)return createBasic(e,'siswa');body.id=selected.id;if(mode==='demo'){setData(d=>({...d,students:d.students.map(s=>s.id===selected.id?{...s,...body}:s)}));close();flash('Data siswa demo diperbarui.');return}try{await api('/api/siswa','PATCH',body);close();flash('Data siswa diperbarui.');load()}catch(e:any){flash(e.message)}}
  async function deleteStudent(st:Student){if(!confirm(`Hapus ${st.name} dari daftar siswa? Data akan dinonaktifkan dari kelas.`))return;if(mode==='demo'){setData(d=>({...d,students:d.students.filter(s=>s.id!==st.id)}));flash('Siswa demo dihapus.');return}try{await api('/api/siswa','DELETE',{id:st.id});flash('Siswa dihapus.');load()}catch(e:any){flash(e.message)}}

  async function saveSubject(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const body:any=Object.fromEntries(new FormData(e.currentTarget).entries());if(selected?.id)body.id=selected.id;if(mode==='demo'){const id=selected?.id||`sub-${Date.now()}`;setData(d=>({...d,subjects:selected?.id?d.subjects.map(s=>s.id===id?{...s,...body,mastery_score:Number(body.mastery_score)}:s):[...d.subjects,{id,...body,mastery_score:Number(body.mastery_score),is_active:true}]}));close();flash('Mata pelajaran demo disimpan.');return}try{await api('/api/mata-pelajaran',selected?.id?'PATCH':'POST',body);close();flash('Mata pelajaran berhasil disimpan.');load()}catch(e:any){flash(e.message)}}
  async function deleteSubject(sb:Subject){if(!confirm(`Hapus mata pelajaran ${sb.name}? Penilaian dan nilai terkait ikut dihapus.`))return;if(mode==='demo'){setData(d=>({...d,subjects:d.subjects.filter(x=>x.id!==sb.id),assessments:d.assessments.filter(a=>a.subject_id!==sb.id),schedules:d.schedules.filter(s=>s.subject_id!==sb.id)}));flash('Mata pelajaran demo dihapus.');return}try{await api('/api/mata-pelajaran','DELETE',{id:sb.id});flash('Mata pelajaran dihapus.');load()}catch(e:any){flash(e.message)}}

  async function saveAssessment(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const body:any=Object.fromEntries(new FormData(e.currentTarget).entries());if(selected?.id)body.id=selected.id;if(mode==='demo'){const sb=data.subjects.find(s=>s.id===body.subject_id);const id=selected?.id||`as-${Date.now()}`;setData(d=>({...d,assessments:selected?.id?d.assessments.map(a=>a.id===id?{...a,...body,subject_name:sb?.name||'',max_score:Number(body.max_score)}:a):[{id,...body,subject_name:sb?.name||'',max_score:Number(body.max_score)},...d.assessments]}));close();flash('Penilaian demo disimpan.');return}try{await api('/api/penilaian',selected?.id?'PATCH':'POST',body);close();flash('Penilaian berhasil disimpan.');load()}catch(e:any){flash(e.message)}}
  async function deleteAssessment(as:Assessment){if(!confirm(`Hapus penilaian ${as.name}? Nilai siswa pada penilaian ini ikut dihapus.`))return;if(mode==='demo'){setData(d=>({...d,assessments:d.assessments.filter(a=>a.id!==as.id),scores:d.scores.filter(s=>s.assessment_id!==as.id)}));flash('Penilaian demo dihapus.');return}try{await api('/api/penilaian','DELETE',{id:as.id});flash('Penilaian dihapus.');load()}catch(e:any){flash(e.message)}}

  async function saveSchedule(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const body:any=Object.fromEntries(new FormData(e.currentTarget).entries());if(selected?.id)body.id=selected.id;if(mode==='demo'){const sb=data.subjects.find(s=>s.id===body.subject_id);const id=selected?.id||`sch-${Date.now()}`;const item={id,...body,subject_name:sb?.name||'',teacher_name:sb?.teacher_name};setData(d=>({...d,schedules:selected?.id?d.schedules.map(x=>x.id===id?item:x):[...d.schedules,item]}));close();flash('Jadwal demo disimpan.');return}try{await api('/api/jadwal-pelajaran',selected?.id?'PATCH':'POST',body);close();flash('Jadwal pelajaran berhasil disimpan.');load()}catch(e:any){flash(e.message)}}
  async function deleteSchedule(sc:Schedule){if(!confirm(`Hapus jadwal ${sc.subject_name} hari ${sc.day_name}?`))return;if(mode==='demo'){setData(d=>({...d,schedules:d.schedules.filter(x=>x.id!==sc.id)}));flash('Jadwal demo dihapus.');return}try{await api('/api/jadwal-pelajaran','DELETE',{id:sc.id});flash('Jadwal dihapus.');load()}catch(e:any){flash(e.message)}}

  function startScores(as:Assessment){const draft:Record<string,{score:string;remedial:string;note:string}>={};data.students.forEach(st=>{const sc=data.scores.find(s=>s.assessment_id===as.id&&s.student_id===st.id);draft[st.id]={score:sc?.score==null?'':String(sc.score),remedial:sc?.remedial_score==null?'':String(sc.remedial_score),note:sc?.note||''}});setScoreDraft(draft);open('nilai',as)}
  async function saveScores(){if(!selected)return;const scores=data.students.map(st=>({student_id:st.id,score:scoreDraft[st.id]?.score===''?null:Number(scoreDraft[st.id]?.score),remedial_score:scoreDraft[st.id]?.remedial===''?null:Number(scoreDraft[st.id]?.remedial),note:scoreDraft[st.id]?.note||''}));if(mode==='demo'){setData(d=>{const keep=d.scores.filter(s=>s.assessment_id!==selected.id);return {...d,scores:[...keep,...scores.map((s,i)=>({id:`demo-score-${Date.now()}-${i}`,assessment_id:selected.id,...s}))]}});close();flash('Nilai demo berhasil disimpan.');return}try{await api('/api/nilai','POST',{assessment_id:selected.id,scores});close();flash('Nilai berhasil disimpan.');load()}catch(e:any){flash(e.message)}}

  async function completeFollow(id:string){if(mode==='demo'){setData(d=>({...d,followUps:d.followUps.map(f=>f.id===id?{...f,status:'Selesai'}:f)}));flash('Tindak lanjut ditandai selesai.');return}try{await api('/api/tindak-lanjut','PATCH',{id,status:'Selesai',result:'Selesai ditindaklanjuti.'});flash('Tindak lanjut selesai.');load()}catch(e:any){flash(e.message)}}

  async function saveClassProfile(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const body:any=Object.fromEntries(new FormData(e.currentTarget).entries());if(mode==='demo'){setData(d=>({...d,profile:{...d.profile,...body}}));flash('Profil kelas demo disimpan.');return}try{await api('/api/profil-kelas','PATCH',body);flash('Profil kelas disimpan.');load()}catch(e:any){flash(e.message)}}

  async function saveAcademicSettings(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const body:any=Object.fromEntries(new FormData(e.currentTarget).entries());if(mode==='demo'){setData(d=>({...d,academicSettings:body}));flash('Pengaturan akademik demo disimpan.');return}try{await api('/api/pengaturan-akademik','PATCH',body);flash('Pengaturan akademik disimpan.');load()}catch(e:any){flash(e.message)}}

  function downloadReport(jenis:string,format:'xlsx'|'pdf',subjectId?:string){if(mode==='demo'){flash('Unduhan laporan tersedia pada akun berlisensi.');return}const qs=new URLSearchParams({jenis,format,bulan:reportMonth});if(subjectId)qs.set('subject_id',subjectId);window.location.href=`/api/laporan/export?${qs.toString()}`}

  const profile=data.profile||{};
  const titles:Record<View,[string,string]>={beranda:['Beranda','Ringkasan kelas dan pekerjaan penting hari ini.'],siswa:['Siswa','Kelola data siswa, orang tua, dan profil kelas.'],kehadiran:['Kehadiran','Catat kehadiran harian dengan cepat dan konsisten.'],akademik:['Akademik','Mata pelajaran, penilaian, nilai, dan remedial dalam satu tempat.'],jadwal:['Jadwal Pelajaran','Atur jadwal mingguan kelas dan guru pengampu.'],catatan:['Catatan Wali Kelas','Dokumentasikan perkembangan dan hal penting siswa.'],prestasi:['Prestasi','Catat pencapaian positif siswa.'],tindak:['Tindak Lanjut','Pastikan setiap hal penting benar-benar diselesaikan.'],orangtua:['Orang Tua','Kontak dan riwayat komunikasi dengan orang tua/wali.'],agenda:['Agenda Kelas','Kegiatan, rapat, dan jadwal khusus kelas.'],laporan:['Pusat Laporan','Unduh laporan kelas dalam Excel atau PDF yang rapi.'],pengaturan:['Pengaturan','Atur kelas, akademik, dan informasi lisensi.']};

  function pageAction(){if(view==='siswa')return <button className="btn btn-primary" onClick={()=>open('siswa')}><Plus size={16}/>Tambah Siswa</button>;if(view==='akademik')return <button className="btn btn-primary" onClick={()=>open('mapel')}><Plus size={16}/>Tambah Mata Pelajaran</button>;if(view==='jadwal')return <button className="btn btn-primary" onClick={()=>open('jadwal')}><Plus size={16}/>Tambah Jadwal</button>;if(view==='catatan')return <button className="btn btn-primary" onClick={()=>open('catatan')}><Plus size={16}/>Tambah Catatan</button>;if(view==='prestasi')return <button className="btn btn-primary" onClick={()=>open('prestasi')}><Plus size={16}/>Tambah Prestasi</button>;if(view==='tindak')return <button className="btn btn-primary" onClick={()=>open('tindak')}><Plus size={16}/>Tambah Tindak Lanjut</button>;if(view==='agenda')return <button className="btn btn-primary" onClick={()=>open('agenda')}><Plus size={16}/>Tambah Agenda</button>;if(view==='orangtua')return <button className="btn btn-primary" onClick={()=>open('komunikasi')}><Plus size={16}/>Catat Komunikasi</button>;return null}

  const Beranda=()=> <>
    <section className="welcome-panel"><div><span className="eyebrow">{profile.class_name||'Kelas aktif'} · {profile.academic_year||''}</span><h2>Selamat datang, {profile.teacher_name||'Wali Kelas'}.</h2><p>Fokus pada hal yang membutuhkan perhatian. Administrasi lainnya KelasKita rapikan di belakang.</p></div><div className="welcome-score"><small>Rata-rata akademik</small><strong>{classAverage===null?'—':classAverage.toFixed(1)}</strong></div></section>
    <div className="stats-grid"><Stat value={data.students.length} label="Siswa aktif"/><Stat value={counts.hadir} label="Hadir hari ini"/><Stat value={attention.length} label="Perlu perhatian"/><Stat value={data.followUps.filter(f=>f.status!=='Selesai').length} label="Tindak lanjut aktif"/></div>
    <div className="grid-2">
      <div className="card"><div className="card-head"><div><h3>Perlu perhatian</h3><div className="subtle">Kehadiran, catatan, dan akademik yang sebaiknya ditinjau.</div></div></div>{attention.length===0?<div className="empty">Belum ada siswa yang membutuhkan perhatian khusus hari ini.</div>:<div className="attention-list">{attention.map(st=>{const warning=studentAcademicWarnings(st.id);const att=data.attendance.find(a=>a.student_id===st.id);const note=data.notes.find(n=>n.student_id===st.id&&String(n.status).includes('Tindak'));const text=warning?`${warning} mata pelajaran di bawah ketuntasan`:note?.title||(`${att?.status||'Perlu dipantau'}`);return <div className="attention-row" key={st.id}><div className="avatar">{initials(st.name)}</div><div className="row-main"><b>{st.name}</b><small>{text}</small></div><button className="btn btn-ghost btn-small" onClick={()=>open('detail',st)}>Lihat</button></div>})}</div>}</div>
      <div className="card"><div className="card-head"><div><h3>Pelajaran hari ini</h3><div className="subtle">{dayToday()}</div></div></div>{todaySchedules.length?<div className="agenda-list">{todaySchedules.map(sc=><div className="agenda-row" key={sc.id}><div className="time-box">{String(sc.start_time).slice(0,5)}</div><div><b>{sc.subject_name}</b><div className="subtle">{sc.teacher_name||'Guru belum diisi'} · {String(sc.end_time).slice(0,5)}</div></div></div>)}</div>:<div className="empty compact">Belum ada jadwal pelajaran hari ini.</div>}</div>
    </div>
    <div className="grid-2 compact-gap"><div className="card"><div className="card-head"><h3>Agenda terdekat</h3><button className="text-button" onClick={()=>setView('agenda')}>Lihat semua <ChevronRight size={14}/></button></div>{data.agendas.slice(0,3).map(a=><div className="agenda-row" key={a.id}><div className="time-box">{a.agenda_time?String(a.agenda_time).slice(0,5):'—'}</div><div><b>{a.title}</b><div className="subtle">{indoDate(a.agenda_date)} · {a.category}</div></div></div>)}{!data.agendas.length&&<div className="empty compact">Belum ada agenda.</div>}</div><div className="card"><div className="card-head"><h3>Aksi cepat</h3></div><div className="quick-actions"><button onClick={()=>setView('kehadiran')}>Ambil Kehadiran</button><button onClick={()=>setView('akademik')}>Kelola Nilai</button><button onClick={()=>open('catatan')}>Tambah Catatan</button><button onClick={()=>setView('laporan')}>Unduh Laporan</button></div></div></div>
  </>;

  const Siswa=()=> <><div className="search-row"><div className="search-box"><Search size={17}/><input className="input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari nama, NIS, NISN, atau orang tua..."/></div><label className="btn btn-soft btn-small" htmlFor="import-siswa">Impor Excel</label><input id="import-siswa" type="file" accept=".xlsx" hidden onChange={e=>{const f=e.target.files?.[0];if(f)importStudents(f);e.currentTarget.value=''}}/><a className="btn btn-ghost btn-small" href={mode==='demo'?'#':'/api/siswa/import'} onClick={e=>{if(mode==='demo'){e.preventDefault();flash('Template tersedia pada akun berlisensi.')}}}>Template</a><span className="pill">{filteredStudents.length} siswa</span></div><div className="student-grid">{filteredStudents.map(st=><article className="student-card" key={st.id}><div className="student-top" onClick={()=>open('detail',st)}><div className="avatar">{initials(st.name)}</div><div className="row-main"><b>{st.name}</b><div className="subtle">NIS {st.nis||'-'} · {st.gender||'Belum lengkap'}</div></div><ChevronRight size={17}/></div><div className="student-meta"><span className="badge badge-good">{st.status||'Aktif'}</span>{studentAcademicWarnings(st.id)>0&&<span className="badge badge-warn">{studentAcademicWarnings(st.id)} akademik</span>}</div><div className="card-actions"><button className="text-button" onClick={()=>open('siswa',st)}><Pencil size={14}/>Ubah</button><button className="text-button danger" onClick={()=>deleteStudent(st)}><Trash2 size={14}/>Hapus</button></div></article>)}{!filteredStudents.length&&<div className="empty">Siswa tidak ditemukan.</div>}</div></>;

  const Kehadiran=()=> <div className="card"><div className="card-head"><div><h3>Kehadiran {indoDate(today)}</h3><div className="subtle">Semua siswa otomatis Hadir. Ubah hanya yang berbeda.</div></div><span className="badge badge-info">{counts.hadir}/{data.students.length} hadir</span></div>{data.students.length===0?<div className="empty">Tambahkan siswa terlebih dahulu.</div>:<div className="attendance-list">{data.students.map(st=><div className="attendance-row" key={st.id}><div className="student-top"><div className="avatar">{initials(st.name)}</div><div><b>{st.name}</b><div className="subtle">NIS {st.nis||'-'}</div></div></div><select className="input" value={attendanceMap[st.id]||'Hadir'} onChange={e=>setAttendanceMap(m=>({...m,[st.id]:e.target.value}))}><option>Hadir</option><option>Sakit</option><option>Izin</option><option>Alfa</option><option>Terlambat</option><option>Dispensasi</option></select></div>)}</div>}<div className="right-actions"><button className="btn btn-primary" onClick={saveAttendance}><Check size={17}/>Simpan Kehadiran</button></div></div>;

  const Akademik=()=>{const subject=data.subjects.find(s=>s.id===selectedSubject);const asets=data.assessments.filter(a=>!selectedSubject||a.subject_id===selectedSubject);const remedials=data.scores.filter(sc=>{const as=data.assessments.find(a=>a.id===sc.assessment_id);const sb=as&&data.subjects.find(s=>s.id===as.subject_id);return as&&sb&&scoreUsed(sc)!==null&&normalizedScore(sc,as)!<n(sb.mastery_score)});return <>
    <div className="segmented"><button className={academicTab==='mapel'?'active':''} onClick={()=>setAcademicTab('mapel')}>Mata Pelajaran</button><button className={academicTab==='penilaian'?'active':''} onClick={()=>setAcademicTab('penilaian')}>Penilaian & Nilai</button><button className={academicTab==='remedial'?'active':''} onClick={()=>setAcademicTab('remedial')}>Remedial <span>{remedials.length}</span></button></div>
    {academicTab==='mapel'&&<div className="subject-grid">{data.subjects.map(sb=>{const vals=data.students.map(st=>subjectFinal(st.id,sb.id)).filter(v=>v!==null) as number[];const avg=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null;const below=data.students.filter(st=>{const v=subjectFinal(st.id,sb.id);return v!==null&&v<n(sb.mastery_score)}).length;return <article className="subject-card" key={sb.id}><div className="subject-accent"/><div className="subject-head"><div><span className="eyebrow">Batas ketuntasan {n(sb.mastery_score)}</span><h3>{sb.name}</h3><p>{sb.teacher_name||'Guru pengampu belum diisi'}</p></div><button className="icon-btn" onClick={()=>open('mapel',sb)}><MoreHorizontal size={18}/></button></div><div className="subject-metrics"><div><small>Rata-rata</small><b>{avg===null?'—':avg.toFixed(1)}</b></div><div><small>Perlu perhatian</small><b>{below}</b></div><div><small>Penilaian</small><b>{data.assessments.filter(a=>a.subject_id===sb.id).length}</b></div></div><div className="card-actions"><button className="text-button" onClick={()=>{setSelectedSubject(sb.id);setAcademicTab('penilaian')}}>Buka penilaian <ChevronRight size={14}/></button><button className="text-button danger" onClick={()=>deleteSubject(sb)}>Hapus</button></div></article>})}{!data.subjects.length&&<div className="empty card">Belum ada mata pelajaran. Tambahkan mata pelajaran pertama.</div>}</div>}
    {academicTab==='penilaian'&&<><div className="academic-toolbar"><select className="input" value={selectedSubject} onChange={e=>setSelectedSubject(e.target.value)}><option value="">Semua mata pelajaran</option>{data.subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button className="btn btn-primary" onClick={()=>open('penilaian')} disabled={!data.subjects.length}><Plus size={16}/>Tambah Penilaian</button></div>{subject&&<div className="academic-summary"><div><span className="eyebrow">{subject.teacher_name||'Guru belum diisi'}</span><h3>{subject.name}</h3></div><div><small>Batas ketuntasan</small><strong>{n(subject.mastery_score)}</strong></div></div>}<div className="assessment-list">{asets.map(as=>{const filled=data.scores.filter(sc=>sc.assessment_id===as.id&&sc.score!==null&&sc.score!==undefined).length;return <div className="assessment-row" key={as.id}><div><span className="badge badge-info">{as.category}</span><h4>{as.name}</h4><p>{indoDate(as.assessment_date)} · {as.semester} · Nilai maksimum {n(as.max_score)}</p></div><div className="assessment-actions"><span className="subtle">{filled}/{data.students.length} terisi</span><button className="btn btn-soft btn-small" onClick={()=>startScores(as)}>Input Nilai</button><button className="icon-btn" onClick={()=>open('penilaian',as)}><Pencil size={15}/></button><button className="icon-btn danger" onClick={()=>deleteAssessment(as)}><Trash2 size={15}/></button></div></div>})}{!asets.length&&<div className="empty card">Belum ada penilaian untuk pilihan ini.</div>}</div></>}
    {academicTab==='remedial'&&<div className="card"><div className="card-head"><div><h3>Siswa perlu remedial</h3><div className="subtle">Nilai yang masih di bawah batas ketuntasan mata pelajaran.</div></div></div><div className="table-wrap"><table className="table"><thead><tr><th>Siswa</th><th>Mata Pelajaran</th><th>Penilaian</th><th>Nilai</th><th>Batas</th></tr></thead><tbody>{remedials.map((sc,i)=>{const st=data.students.find(s=>s.id===sc.student_id);const as=data.assessments.find(a=>a.id===sc.assessment_id)!;const sb=data.subjects.find(s=>s.id===as.subject_id)!;return <tr key={`${sc.assessment_id}-${sc.student_id}-${i}`}><td><strong>{st?.name}</strong></td><td>{sb?.name}</td><td>{as?.name}</td><td>{scoreUsed(sc)?.toFixed(0)}</td><td>{n(sb?.mastery_score)}</td></tr>})}{!remedials.length&&<tr><td colSpan={5}><div className="empty compact">Tidak ada nilai yang membutuhkan remedial.</div></td></tr>}</tbody></table></div></div>}
  </>};

  const Jadwal=()=> <><div className="schedule-week">{dayOrder.slice(0,6).map(day=><section className="schedule-day" key={day}><div className="schedule-day-head"><h3>{day}</h3><span>{data.schedules.filter(s=>s.day_name===day).length} pelajaran</span></div>{data.schedules.filter(s=>s.day_name===day).map(sc=><div className="schedule-item" key={sc.id}><div className="schedule-time">{String(sc.start_time).slice(0,5)}<small>{String(sc.end_time).slice(0,5)}</small></div><div className="row-main"><b>{sc.subject_name}</b><small>{sc.teacher_name||'Guru belum diisi'}{sc.room?` · ${sc.room}`:''}</small></div><button className="icon-btn" onClick={()=>open('jadwal',sc)}><Pencil size={15}/></button><button className="icon-btn danger" onClick={()=>deleteSchedule(sc)}><Trash2 size={15}/></button></div>)}{!data.schedules.some(s=>s.day_name===day)&&<div className="empty compact">Belum ada jadwal.</div>}</section>)}</div></>;

  const Catatan=()=> <ListTable headers={['Siswa','Kategori','Catatan','Status','Tanggal']} rows={data.notes.map(x=>[x.student_name,x.category,<><strong>{x.title}</strong><br/><small className="subtle">{x.content}</small></>,<span className={`badge ${statusClass(x.status)}`}>{x.status}</span>,indoDate(x.occurred_at)])} empty="Belum ada catatan wali kelas."/>;
  const Prestasi=()=> <ListTable headers={['Siswa','Prestasi','Kategori','Tingkat','Tanggal']} rows={data.achievements.map(x=>[x.student_name,<><strong>{x.title}</strong>{x.rank&&<><br/><small className="subtle">{x.rank}</small></>}</>,x.category,x.level||'-',indoDate(x.achieved_at)])} empty="Belum ada prestasi yang dicatat."/>;
  const Tindak=()=> <div className="attention-list">{data.followUps.map(f=><div className="card action-card" key={f.id}><div className="row-main"><div className="inline-wrap"><b>{f.title}</b><span className={`badge ${statusClass(f.status)}`}>{f.status}</span></div><div className="subtle">{f.student_name} · Target {indoDate(f.due_date)}</div><p>{f.action}</p></div>{f.status!=='Selesai'&&<button className="btn btn-soft" onClick={()=>completeFollow(f.id)}>Tandai Selesai</button>}</div>)}{!data.followUps.length&&<div className="empty">Belum ada tindak lanjut.</div>}</div>;
  const OrangTua=()=> <><div className="student-grid">{data.students.map(st=><article className="student-card" key={st.id}><div className="student-top"><div className="avatar">{initials(st.name)}</div><div className="row-main"><b>{st.name}</b><div className="subtle">{st.guardian_name||'Orang tua belum diisi'}</div></div></div><div className="card-actions">{st.guardian_phone?<a className="btn btn-soft btn-small" target="_blank" href={`https://wa.me/${String(st.guardian_phone).replace(/\D/g,'').replace(/^0/,'62')}`}>WhatsApp</a>:<span className="subtle">Nomor belum tersedia.</span>}</div></article>)}</div><div className="card section-gap"><div className="card-head"><h3>Riwayat komunikasi</h3></div>{data.communications.length?<div className="agenda-list">{data.communications.map(c=><div className="agenda-row" key={c.id}><div className="time-box">{c.method}</div><div><b>{c.student_name} · {c.topic}</b><div className="subtle">{c.result||'Tidak ada catatan hasil'} · {indoDate(c.communicated_at)}</div></div></div>)}</div>:<div className="empty">Belum ada komunikasi yang dicatat.</div>}</div></>;
  const Agenda=()=> <div className="card"><div className="agenda-list">{data.agendas.map(a=><div className="agenda-row" key={a.id}><div className="time-box"><Clock3 size={14}/><br/>{a.agenda_time?String(a.agenda_time).slice(0,5):'—'}</div><div className="row-main"><b>{a.title}</b><div className="subtle">{indoDate(a.agenda_date)} · {a.category}</div>{a.description&&<p className="small-copy">{a.description}</p>}</div><span className={`badge ${a.is_done?'badge-good':'badge-info'}`}>{a.is_done?'Selesai':'Terjadwal'}</span></div>)}{!data.agendas.length&&<div className="empty">Belum ada agenda kelas.</div>}</div></div>;

  const reports=[['siswa','Daftar Siswa','Identitas, kontak, orang tua, dan status siswa.'],['kehadiran','Rekap Kehadiran','Hadir, sakit, izin, alfa, terlambat, dan dispensasi per bulan.'],['nilai','Laporan Nilai','Seluruh penilaian, nilai awal, remedial, dan nilai yang digunakan.'],['prestasi','Rekap Prestasi','Daftar pencapaian dan prestasi siswa.'],['catatan','Catatan Wali Kelas','Catatan perkembangan, kategori, dan status.'],['tindak','Tindak Lanjut','Tindakan, target, status, dan hasil.'],['komunikasi','Komunikasi Orang Tua','Riwayat komunikasi dengan orang tua atau wali.'],['agenda','Agenda Kelas','Agenda, kegiatan, dan status pelaksanaan.']] as const;
  const Laporan=()=> <><div className="report-toolbar"><div><label>Periode laporan kehadiran</label><input className="input" type="month" value={reportMonth} onChange={e=>setReportMonth(e.target.value)}/></div><div className="subtle">Excel dibuat dengan judul, filter, lebar kolom rapi, dan header beku. PDF siap dibagikan atau dicetak.</div></div><div className="report-grid">{reports.map(([key,title,desc])=><article className="report-card" key={key}><span className="report-kicker">LAPORAN</span><h3>{title}</h3><p>{desc}</p>{key==='nilai'&&<select className="input report-select" value={selectedSubject} onChange={e=>setSelectedSubject(e.target.value)}><option value="">Semua mata pelajaran</option>{data.subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>}<div className="report-actions"><button className="btn btn-soft" onClick={()=>downloadReport(key,'xlsx',key==='nilai'?selectedSubject:undefined)}><Download size={15}/>Excel</button><button className="btn btn-ghost" onClick={()=>downloadReport(key,'pdf',key==='nilai'?selectedSubject:undefined)}><Download size={15}/>PDF</button></div></article>)}</div></>;

  const Pengaturan=()=> <div className="settings-grid"><form className="card" onSubmit={saveClassProfile}><div className="card-head"><div><h3>Profil Kelas</h3><div className="subtle">Admin kelas bebas memperbarui identitas ruang kerjanya.</div></div></div><Field label="Wali Kelas"><input className="input" name="teacher_name" defaultValue={profile.teacher_name}/></Field><Field label="Sekolah"><input className="input" name="school_name" defaultValue={profile.school_name}/></Field><div className="form-grid"><Field label="Kelas"><input className="input" name="class_name" defaultValue={profile.class_name}/></Field><Field label="Tahun Ajaran"><input className="input" name="academic_year" defaultValue={profile.academic_year}/></Field></div><button className="btn btn-primary" style={{width:'100%'}}>Simpan Profil</button></form><form className="card" onSubmit={saveAcademicSettings}><div className="card-head"><div><h3>Pengaturan Akademik</h3><div className="subtle">Atur semester aktif dan bobot nilai.</div></div></div><div className="form-grid"><Field label="Semester Aktif"><select className="input" name="active_semester" defaultValue={data.academicSettings.active_semester}><option>Ganjil</option><option>Genap</option></select></Field><Field label="Perhitungan Nilai"><select className="input" name="calculation_mode" defaultValue={data.academicSettings.calculation_mode}><option>Otomatis</option><option>Rata-rata Sederhana</option></select></Field><Field label="Bobot Tugas Harian (%)"><input className="input" name="daily_weight" type="number" defaultValue={n(data.academicSettings.daily_weight)}/></Field><Field label="Bobot Ulangan Harian (%)"><input className="input" name="quiz_weight" type="number" defaultValue={n(data.academicSettings.quiz_weight)}/></Field><Field label="Bobot Semester (%)"><input className="input" name="semester_weight" type="number" defaultValue={n(data.academicSettings.semester_weight)}/></Field></div><div className="right-actions"><button className="btn btn-primary">Simpan Pengaturan</button></div></form><div className="card"><div className="card-head"><h3>Akun & Lisensi</h3></div><p className="subtle">{mode==='demo'?'Mode Demo menggunakan data lokal dan tidak menulis ke Neon.':'Data lisensi ini terisolasi dari pelanggan lain.'}</p><button className="btn btn-danger" onClick={logout}><LogOut size={16}/>{mode==='demo'?'Keluar dari Demo':'Keluar dari Akun'}</button></div></div>;

  const pages:Record<View,React.ReactNode>={beranda:<Beranda/>,siswa:<Siswa/>,kehadiran:<Kehadiran/>,akademik:<Akademik/>,jadwal:<Jadwal/>,catatan:<Catatan/>,prestasi:<Prestasi/>,tindak:<Tindak/>,orangtua:<OrangTua/>,agenda:<Agenda/>,laporan:<Laporan/>,pengaturan:<Pengaturan/>};

  return <div className="app-shell">
    <aside className="sidebar"><div className="sidebar-brand"><Brand href={mode==='demo'?'/demo':'/aplikasi'} inverse/></div><div className="side-class"><small>KELAS AKTIF</small><b>{profile.class_name||'KelasKita'}</b><span>{profile.academic_year||''}</span></div><nav className="side-nav">{nav.map(([k,label,I])=><button key={k} className={view===k?'active':''} onClick={()=>setView(k as View)}><I size={18}/><span>{label}</span></button>)}</nav><div className="sidebar-foot"><button onClick={logout}><LogOut size={17}/><span>{mode==='demo'?'Keluar Demo':'Keluar'}</span></button></div></aside>
    <main className="app-main"><header className="topbar"><div className="topbar-left"><b>{profile.class_name||'KelasKita'}</b><small>{profile.school_name||'Ruang kerja wali kelas'}</small></div><div className="top-actions"><span className={`license-dot ${mode==='demo'?'demo':''}`}/><span className="hide-mobile">{mode==='demo'?'Mode Demo':'Lisensi Aktif'}</span></div></header><div className="app-content">{mode==='demo'&&<div className="demo-banner"><span><b>Mode Demo.</b> Semua perubahan hanya tersimpan selama halaman ini terbuka.</span><button className="text-button" onClick={()=>router.push('/masuk')}>Punya lisensi? Masuk</button></div>}<div className="page-head"><div><span className="eyebrow">KELASKITA</span><h1>{titles[view][0]}</h1><p>{titles[view][1]}</p></div>{pageAction()}</div>{loading?<div className="loading-card">Menyiapkan ruang kelas...</div>:pages[view]}</div></main>
    <nav className="mobile-nav">{(['beranda','siswa','kehadiran','agenda'] as View[]).map(k=>{const x=nav.find(nv=>nv[0]===k)!;const I=x[2];return <button key={k} className={view===k?'active':''} onClick={()=>{setView(k);setMoreOpen(false)}}><I size={19}/>{x[1]}</button>})}<button className={moreOpen||['akademik','jadwal','catatan','prestasi','tindak','orangtua','laporan','pengaturan'].includes(view)?'active':''} onClick={()=>setMoreOpen(v=>!v)}><Menu size={19}/>Lainnya</button></nav>
    {moreOpen&&<div className="mobile-more"><div className="mobile-more-grid">{(['akademik','jadwal','catatan','prestasi','tindak','orangtua','laporan','pengaturan'] as View[]).map(k=>{const x=nav.find(nv=>nv[0]===k)!;const I=x[2];return <button key={k} onClick={()=>{setView(k);setMoreOpen(false)}}><span><I size={18}/></span>{x[1]}</button>})}</div></div>}
    {modal&&<Modal type={modal} selected={selected} students={data.students} subjects={data.subjects} settings={data.academicSettings} close={close} basic={createBasic} saveStudent={saveStudent} saveSubject={saveSubject} saveAssessment={saveAssessment} saveSchedule={saveSchedule} scoreDraft={scoreDraft} setScoreDraft={setScoreDraft} saveScores={saveScores} today={today} data={data}/>} {toast&&<div className="toast">{toast}</div>}
  </div>
}

function Modal({type,selected,students,subjects,settings,close,basic,saveStudent,saveSubject,saveAssessment,saveSchedule,scoreDraft,setScoreDraft,saveScores,today,data}:any){
  const studentSelect=<Field label="Siswa"><select className="input" name="student_id" defaultValue={selected?.student_id||selected?.id||''} required><option value="">Pilih siswa</option>{students.map((s:Student)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field>;
  if(type==='detail'&&selected){const notes=data.notes.filter((x:any)=>x.student_id===selected.id);const achievements=data.achievements.filter((x:any)=>x.student_id===selected.id);const follow=data.followUps.filter((x:any)=>x.student_id===selected.id);const academic=subjects.map((sb:Subject)=>{const assessments=data.assessments.filter((a:Assessment)=>a.subject_id===sb.id);const vals=assessments.map((a:Assessment)=>{const sc=data.scores.find((s:Score)=>s.assessment_id===a.id&&s.student_id===selected.id);return sc?scoreUsed(sc):null}).filter((v:any)=>v!==null) as number[];return {name:sb.name,avg:vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null,kkm:n(sb.mastery_score)}});return <Dialog close={close} title={selected.name} subtitle={`NIS ${selected.nis||'-'} · NISN ${selected.nisn||'-'}`}><div className="profile-metrics"><Metric label="Catatan" value={notes.length}/><Metric label="Prestasi" value={achievements.length}/><Metric label="Tindak lanjut" value={follow.filter((f:any)=>f.status!=='Selesai').length}/></div><div className="detail-block"><h3>Orang Tua/Wali</h3><b>{selected.guardian_name||'Belum diisi'}</b><p>{selected.guardian_phone||'Nomor belum diisi'}</p></div><div className="detail-block"><h3>Ringkasan Akademik</h3>{academic.map((a:any)=><div className="academic-line" key={a.name}><span>{a.name}</span><b className={a.avg!==null&&a.avg<a.kkm?'text-warn':''}>{a.avg===null?'—':a.avg.toFixed(1)}</b></div>)}</div></Dialog>}
  if(type==='nilai'&&selected)return <Dialog close={close} title={`Input Nilai · ${selected.name}`} subtitle={`${selected.subject_name} · Nilai maksimum ${selected.max_score}`} wide><div className="score-table"><div className="score-head"><span>Siswa</span><span>Nilai</span><span>Remedial</span><span>Catatan</span></div>{students.map((st:Student)=><div className="score-row" key={st.id}><div><b>{st.name}</b><small>NIS {st.nis||'-'}</small></div><input className="input" type="number" min="0" max={selected.max_score} value={scoreDraft[st.id]?.score||''} onChange={e=>setScoreDraft((d:any)=>({...d,[st.id]:{...d[st.id],score:e.target.value}}))}/><input className="input" type="number" min="0" max={selected.max_score} value={scoreDraft[st.id]?.remedial||''} onChange={e=>setScoreDraft((d:any)=>({...d,[st.id]:{...d[st.id],remedial:e.target.value}}))}/><input className="input" value={scoreDraft[st.id]?.note||''} onChange={e=>setScoreDraft((d:any)=>({...d,[st.id]:{...d[st.id],note:e.target.value}}))} placeholder="Opsional"/></div>)}</div><div className="modal-actions"><button className="btn btn-ghost" onClick={close}>Batal</button><button className="btn btn-primary" onClick={saveScores}>Simpan Semua Nilai</button></div></Dialog>;
  if(type==='siswa')return <Dialog close={close} title={selected?'Ubah Data Siswa':'Tambah Siswa'} subtitle="Data dapat diperbarui kapan saja."><form onSubmit={saveStudent}><div className="form-grid"><Field label="Nama Lengkap"><input className="input" name="name" required defaultValue={selected?.name}/></Field><Field label="Jenis Kelamin"><select className="input" name="gender" defaultValue={selected?.gender||''}><option value="">Pilih</option><option>Laki-laki</option><option>Perempuan</option></select></Field><Field label="NIS"><input className="input" name="nis" defaultValue={selected?.nis}/></Field><Field label="NISN"><input className="input" name="nisn" defaultValue={selected?.nisn}/></Field><Field label="Tempat Lahir"><input className="input" name="birth_place" defaultValue={selected?.birth_place}/></Field><Field label="Tanggal Lahir"><input className="input" type="date" name="birth_date" defaultValue={selected?.birth_date?.slice?.(0,10)||''}/></Field><Field label="Nama Orang Tua/Wali"><input className="input" name="guardian_name" defaultValue={selected?.guardian_name}/></Field><Field label="Nomor Orang Tua/Wali"><input className="input" name="guardian_phone" defaultValue={selected?.guardian_phone}/></Field><Field label="Nomor Siswa"><input className="input" name="phone" defaultValue={selected?.phone}/></Field><Field label="Status"><select className="input" name="status" defaultValue={selected?.status||'Aktif'}><option>Aktif</option><option>Pindah</option><option>Lulus</option><option>Tidak Aktif</option></select></Field><Field label="Alamat" full><textarea className="input textarea" name="address" defaultValue={selected?.address}/></Field></div><Actions close={close}/></form></Dialog>;
  if(type==='mapel')return <Dialog close={close} title={selected?'Ubah Mata Pelajaran':'Tambah Mata Pelajaran'} subtitle="Atur guru pengampu dan batas ketuntasan."><form onSubmit={saveSubject}><Field label="Nama Mata Pelajaran"><input className="input" name="name" required defaultValue={selected?.name}/></Field><Field label="Guru Pengampu"><input className="input" name="teacher_name" defaultValue={selected?.teacher_name}/></Field><Field label="Batas Ketuntasan"><input className="input" type="number" min="0" max="100" name="mastery_score" defaultValue={selected?.mastery_score||75}/></Field><Actions close={close}/></form></Dialog>;
  if(type==='penilaian')return <Dialog close={close} title={selected?'Ubah Penilaian':'Tambah Penilaian'} subtitle="Tugas, ulangan, PTS, PAS, atau penilaian lain."><form onSubmit={saveAssessment}><Field label="Mata Pelajaran"><select className="input" name="subject_id" required defaultValue={selected?.subject_id||subjects[0]?.id||''}>{subjects.map((s:Subject)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="Nama Penilaian"><input className="input" name="name" required defaultValue={selected?.name} placeholder="Contoh: UH 1"/></Field><div className="form-grid"><Field label="Jenis"><select className="input" name="category" defaultValue={selected?.category||'Tugas Harian'}>{categories.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Semester"><select className="input" name="semester" defaultValue={selected?.semester||settings.active_semester}><option>Ganjil</option><option>Genap</option></select></Field><Field label="Tanggal"><input className="input" type="date" name="assessment_date" defaultValue={selected?.assessment_date?.slice?.(0,10)||today}/></Field><Field label="Nilai Maksimum"><input className="input" type="number" min="1" name="max_score" defaultValue={selected?.max_score||100}/></Field></div><Actions close={close}/></form></Dialog>;
  if(type==='jadwal')return <Dialog close={close} title={selected?'Ubah Jadwal Pelajaran':'Tambah Jadwal Pelajaran'} subtitle="Jadwal rutin mingguan kelas."><form onSubmit={saveSchedule}><Field label="Mata Pelajaran"><select className="input" name="subject_id" required defaultValue={selected?.subject_id||subjects[0]?.id||''}>{subjects.map((s:Subject)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><div className="form-grid"><Field label="Hari"><select className="input" name="day_name" defaultValue={selected?.day_name||'Senin'}>{dayOrder.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Ruangan"><input className="input" name="room" defaultValue={selected?.room}/></Field><Field label="Jam Mulai"><input className="input" type="time" name="start_time" required defaultValue={selected?.start_time?.slice?.(0,5)||'07:30'}/></Field><Field label="Jam Selesai"><input className="input" type="time" name="end_time" required defaultValue={selected?.end_time?.slice?.(0,5)||'09:00'}/></Field></div><Actions close={close}/></form></Dialog>;
  if(type==='catatan')return <Dialog close={close} title="Tambah Catatan"><form onSubmit={(e)=>basic(e,'catatan')}>{studentSelect}<div className="form-grid"><Field label="Kategori"><select className="input" name="category"><option>Akademik</option><option>Kehadiran</option><option>Sikap</option><option>Sosial</option><option>Kedisiplinan</option><option>Prestasi</option><option>Orang Tua</option><option>Umum</option></select></Field><Field label="Status"><select className="input" name="status"><option>Informasi</option><option>Perlu Perhatian</option><option>Perlu Tindak Lanjut</option><option>Selesai</option></select></Field></div><Field label="Judul"><input className="input" name="title" required/></Field><Field label="Catatan"><textarea className="input textarea" name="content" required/></Field><Actions close={close}/></form></Dialog>;
  if(type==='prestasi')return <Dialog close={close} title="Tambah Prestasi"><form onSubmit={(e)=>basic(e,'prestasi')}>{studentSelect}<Field label="Nama Prestasi"><input className="input" name="title" required/></Field><div className="form-grid"><Field label="Kategori"><select className="input" name="category"><option>Akademik</option><option>Seni</option><option>Olahraga</option><option>Organisasi</option><option>Keagamaan</option><option>Teknologi</option><option>Lainnya</option></select></Field><Field label="Tingkat"><input className="input" name="level" placeholder="Sekolah / Kota / Provinsi"/></Field><Field label="Tanggal"><input className="input" type="date" name="achieved_at" defaultValue={today}/></Field></div><Actions close={close}/></form></Dialog>;
  if(type==='tindak')return <Dialog close={close} title="Tambah Tindak Lanjut"><form onSubmit={(e)=>basic(e,'tindak')}>{studentSelect}<Field label="Judul"><input className="input" name="title" required/></Field><Field label="Tindakan"><textarea className="input textarea" name="action" required/></Field><Field label="Target"><input className="input" type="date" name="due_date"/></Field><Actions close={close}/></form></Dialog>;
  if(type==='agenda')return <Dialog close={close} title="Tambah Agenda"><form onSubmit={(e)=>basic(e,'agenda')}><Field label="Judul Agenda"><input className="input" name="title" required/></Field><div className="form-grid"><Field label="Kategori"><input className="input" name="category" defaultValue="Kegiatan"/></Field><Field label="Tanggal"><input className="input" type="date" name="agenda_date" required defaultValue={today}/></Field><Field label="Waktu"><input className="input" type="time" name="agenda_time"/></Field></div><Field label="Keterangan"><textarea className="input textarea" name="description"/></Field><Actions close={close}/></form></Dialog>;
  if(type==='komunikasi')return <Dialog close={close} title="Catat Komunikasi Orang Tua"><form onSubmit={(e)=>basic(e,'komunikasi')}>{studentSelect}<div className="form-grid"><Field label="Metode"><select className="input" name="method"><option>WhatsApp</option><option>Telepon</option><option>Tatap Muka</option><option>Surat</option><option>Lainnya</option></select></Field><Field label="Topik"><input className="input" name="topic" required/></Field></div><Field label="Hasil"><textarea className="input textarea" name="result"/></Field><Actions close={close}/></form></Dialog>;
  return null;
}

function Dialog({close,title,subtitle,children,wide=false}:any){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className={`modal ${wide?'modal-wide':''}`}><div className="modal-head"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><button className="icon-btn" onClick={close}><X size={18}/></button></div>{children}</div></div>}
function Actions({close}:any){return <div className="modal-actions"><button type="button" className="btn btn-ghost" onClick={close}>Batal</button><button className="btn btn-primary">Simpan</button></div>}
function Field({label,children,full=false}:any){return <div className={`field ${full?'full':''}`}><label>{label}</label>{children}</div>}
function Stat({value,label}:{value:any;label:string}){return <div className="stat-card"><small>{label}</small><strong>{value}</strong></div>}
function Metric({label,value}:{label:string;value:any}){return <div className="metric"><small>{label}</small><b>{value}</b></div>}
function Info({label,value}:{label:string;value:any}){return <div className="info-row"><span>{label}</span><b>{value||'-'}</b></div>}
function ListTable({headers,rows,empty}:{headers:string[];rows:any[][];empty:string}){return <div className="table-wrap"><table className="table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}{!rows.length&&<tr><td colSpan={headers.length}><div className="empty">{empty}</div></td></tr>}</tbody></table></div>}
